import {NextResponse} from 'next/server';
import {createHash} from 'crypto';
import {identity,db} from '@/lib/supabase';
import {sameOrigin} from '@/lib/access';
import {defaults} from '@/lib/model';
import {recipients} from '@/lib/email';
import {replySchema,visitReply,calendlyLink} from '@/lib/visit-reply';
export async function GET(){const user=await identity();if(user?.role!=='admin')return NextResponse.json({error:'Accès refusé.'},{status:403});return NextResponse.json({ready:!!(process.env.RESEND_API_KEY&&process.env.MAIL_FROM)})}
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({error:'Origine refusée.'},{status:403});const user=await identity();if(user?.role!=='admin')return NextResponse.json({error:'Accès refusé.'},{status:403});let input;try{input=replySchema.safeParse(await req.json())}catch{return NextResponse.json({error:'Données invalides.'},{status:400})}if(!input.success)return NextResponse.json({error:'Vérifiez le destinataire et la date.'},{status:400});const p=input.data;const client=await db();const r=(await client.from('records').select('*').eq('id',p.id).eq('kind','request').maybeSingle()).data;if(!r)return NextResponse.json({error:'Demande introuvable.'},{status:404});if(r.version!==p.version)return NextResponse.json({error:'Cette demande a changé. Rechargez le dossier.'},{status:409});const settings={...defaults,...(await client.from('records').select('data').eq('kind','settings').limit(1).maybeSingle()).data?.data};if(p.includeCalendly&&!calendlyLink(settings.calendly_url))return NextResponse.json({error:'Ajoutez d’abord votre lien Calendly dans les paramètres.'},{status:400});if(!p.date&&!p.includeCalendly&&!p.message.trim())return NextResponse.json({error:'Proposez une date ou rédigez un message.'},{status:400});let draft;try{draft=visitReply({...p,name:r.data.name},settings)}catch{return NextResponse.json({error:'Date invalide.'},{status:400})}const reply={...p,...draft,saved_at:new Date().toISOString()};if(p.action==='send'){
 if(!process.env.RESEND_API_KEY||!process.env.MAIL_FROM)return NextResponse.json({error:'L’envoi direct n’est pas encore activé. Enregistrez le brouillon ou ouvrez-le dans votre messagerie.'},{status:503});
 const key=createHash('sha256').update(JSON.stringify({id:p.id,version:p.version,email:p.email,cc:p.cc,...draft})).digest('hex');
 const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({from:process.env.MAIL_FROM,...recipients(p.email,p.cc),reply_to:settings.email,...draft})});const result=await response.json();await client.from('deliveries').insert({record_id:r.id,recipient:[p.email,...p.cc].join(', '),status:response.ok?'accepted':'failed',provider_id:result.id||null});if(!response.ok)return NextResponse.json({error:'Le service de courriel a refusé l’envoi.'},{status:502});
 }
 const {data,error}=await client.from('records').update({data:{...r.data,visit_reply:reply,...(p.action==='send'?{visit_reply_sent_at:new Date().toISOString()}: {})},version:r.version+1,updated_at:new Date().toISOString()}).eq('id',r.id).eq('version',p.version).select().maybeSingle();if(error||!data)return NextResponse.json({error:p.action==='send'?'Courriel transmis, mais historique à recharger. Ne renvoyez pas immédiatement.':'Le dossier a changé. Rechargez avant de réessayer.'},{status:409});return NextResponse.json({record:data,...draft,message:p.action==='send'?'Proposition transmise au service de courriel.':'Brouillon enregistré. Aucun courriel envoyé.'})}
