'use client';
import {CalendarDays,ChevronLeft,ChevronRight,FileText,FolderKanban,GripVertical,MessageSquare,Plus,Route,Send,StickyNote,Users,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import type {PointerEvent} from 'react';
import {money,totals,type RecordItem} from '@/lib/model';

type Props={client:RecordItem;records:RecordItem[];ownUserId:string;onOpen:(id:string)=>void;onMessage:()=>void;onSendMessage:(body:string)=>Promise<void>;onSaveNotes:(notes:string)=>Promise<void>;onAddTask:()=>void;onAddProject:()=>void;onAddPhase:(projectId:string)=>void;onSchedule:(date:string)=>void;onRefresh:()=>void};
const title=(r:RecordItem)=>String(r.data.title||r.data.number||r.data.name||'Élément du dossier');
const day=(value:unknown)=>String(value||'').slice(0,10);
const colors=['#6e9278','#b48452','#638aa2','#9a7189'];

export default function ClientCockpit({client,records,ownUserId,onOpen,onMessage,onSendMessage,onSaveNotes,onAddTask,onAddProject,onAddPhase,onSchedule,onRefresh}:Props){
 const related=records.filter(record=>record.client_id===client.id),projects=related.filter(record=>record.kind==='project'&&!record.data.archived),tasks=related.filter(record=>record.kind==='task'),phases=related.filter(record=>record.kind==='phase'&&!record.data.archived),visits=related.filter(record=>record.kind==='visit').sort((a,b)=>day(a.data.date||a.data.start).localeCompare(day(b.data.date||b.data.start))),messages=related.filter(record=>record.kind==='message'&&record.data.visibility!=='internal').sort((a,b)=>a.created_at.localeCompare(b.created_at)),documents=related.filter(record=>record.kind==='document');
 const [quick,setQuick]=useState<'messages'|'agenda'|null>(null),[message,setMessage]=useState(''),[sending,setSending]=useState(false),[noteDraft,setNoteDraft]=useState(String(client.data.notes||'')),[noteStatus,setNoteStatus]=useState(''),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[position,setPosition]=useState({x:0,y:0}),[drag,setDrag]=useState<{x:number;y:number;left:number;top:number}|null>(null);
 const phaseFor=(projectId:string)=>phases.filter(phase=>phase.project_id===projectId);
 const financeFor=(project:RecordItem)=>{const projectRecords=related.filter(record=>record.project_id===project.id);const quotes=projectRecords.filter(record=>record.kind==='quote'&&record.data.status==='Accepté');const contracts=projectRecords.filter(record=>record.kind==='contract'&&record.data.status==='Signé');const invoices=projectRecords.filter(record=>record.kind==='invoice'&&!['Brouillon','Annulée'].includes(String(record.data.status)));const linkedQuoteIds=new Set(contracts.map(contract=>String(contract.data.quote_id||'')).filter(Boolean));const contractValue=contracts.reduce((sum,contract)=>sum+(Number(contract.data.amount)||totals(contract.data).total),0)+quotes.filter(quote=>!linkedQuoteIds.has(quote.id)).reduce((sum,quote)=>sum+totals(quote.data).total,0);const invoiced=invoices.reduce((sum,invoice)=>sum+totals(invoice.data).total,0);const paid=invoices.reduce((sum,invoice)=>sum+Number(invoice.data.paid||0),0);return {contractValue,invoiced,paid,outstanding:Math.max(0,invoiced-paid),balance:Math.max(0,contractValue-invoiced)}};
 const progress=(project:RecordItem)=>{const ownPhases=phaseFor(project.id);if(ownPhases.length)return Math.round(ownPhases.reduce((total,phase)=>total+Math.max(0,Math.min(100,Number(phase.data.progress||0))),0)/ownPhases.length);const ownTasks=tasks.filter(task=>task.project_id===project.id);return ownTasks.length?Math.round(ownTasks.filter(task=>task.data.status==='Validée').length/ownTasks.length*100):0};
 const cells=useMemo(()=>{const offset=(month.getDay()+6)%7;return Array.from({length:42},(_,index)=>new Date(month.getFullYear(),month.getMonth(),index-offset+1))},[month]);
 const events=(value:Date)=>visits.filter(visit=>day(visit.data.date||visit.data.start)===value.toISOString().slice(0,10));
 useEffect(()=>{if(!quick)return;const previous=document.documentElement.style.overflow;document.documentElement.style.overflow='hidden';return()=>{document.documentElement.style.overflow=previous}},[quick]);
 useEffect(()=>{if(quick!=='messages')return;onRefresh();const timer=window.setInterval(onRefresh,5000);return()=>window.clearInterval(timer)},[quick,onRefresh]);
 useEffect(()=>{const saved=String(client.data.notes||'');if(noteDraft===saved)return;const timer=window.setTimeout(()=>{setNoteStatus('Enregistrement…');void onSaveNotes(noteDraft).then(()=>setNoteStatus('Enregistrée dans le dossier.')).catch(()=>setNoteStatus('Hors ligne : la note reste sur cet appareil.'))},650);return()=>window.clearTimeout(timer)},[noteDraft,client.data.notes,onSaveNotes]);
 async function submit(event:React.FormEvent){event.preventDefault();if(!message.trim()||sending)return;setSending(true);try{await onSendMessage(message.trim());setMessage('');onRefresh()}finally{setSending(false)}}
 function down(event:PointerEvent<HTMLElement>){if(window.matchMedia('(max-width:640px)').matches)return;event.currentTarget.setPointerCapture(event.pointerId);setDrag({x:event.clientX,y:event.clientY,left:position.x,top:position.y})}
 function move(event:PointerEvent<HTMLElement>){if(drag)setPosition({x:Math.max(-640,Math.min(640,drag.left+event.clientX-drag.x)),y:Math.max(-300,Math.min(300,drag.top+event.clientY-drag.y))})}
 return <section className="client-cockpit"><header className="client-cockpit-head"><div className="client-avatar-large">{String(client.data.name||'?')[0].toUpperCase()}</div><div className="client-identity"><p className="eyebrow">DOSSIER CLIENT</p><h2>{client.data.name}</h2><div className="client-contacts"><a href={'mailto:'+(client.data.email||'')}>{client.data.email||'Courriel à ajouter'}</a><a href={'tel:'+(client.data.phone||'')}>{client.data.phone||'Téléphone à ajouter'}</a><span>{client.data.address||'Adresse à ajouter'}</span></div></div><div className="client-head-actions"><button className="btn secondary" onClick={onAddProject}><FolderKanban size={17}/>Nouveau projet</button><button className="btn secondary" onClick={onAddTask}><StickyNote size={17}/>Tâche sans projet</button><button className="btn primary" onClick={()=>setQuick('messages')}><MessageSquare size={17}/>Message au client</button><a className="btn secondary" href={'tel:'+(client.data.phone||'')}><Users size={17}/>Appeler</a></div></header><section className="client-bento" aria-label="Vue d’ensemble client"><article className="client-bento-intro"><p className="eyebrow">RELATION CLIENT</p><h3>{projects.length?'Un dossier actif, tout au même endroit.':'Prêt à démarrer un premier projet.'}</h3><p>Messages, documents et avancement restent rattachés à cette fiche.</p><button type="button" onClick={()=>setQuick('messages')}><MessageSquare size={16}/>Ouvrir la conversation</button></article><button type="button" className="client-bento-metric" onClick={onAddProject}><FolderKanban size={18}/><span>Projets</span><strong>{projects.length}</strong><small>Ajouter ou ouvrir un chantier</small></button><button type="button" className="client-bento-metric" onClick={()=>setQuick('agenda')}><CalendarDays size={18}/><span>Rendez-vous</span><strong>{visits.length}</strong><small>{visits[0]?(visits[0].data.date||visits[0].data.start):'Aucune visite prévue'}</small></button><button type="button" className="client-bento-metric" onClick={()=>setQuick('messages')}><MessageSquare size={18}/><span>Messages</span><strong>{messages.length}</strong><small>{messages.at(-1)?.data.sender||'Aucun message'}</small></button><article className="client-bento-files"><FileText size={18}/><div><span>Documents du dossier</span><strong>{documents.length}</strong><small>Plans, photos et documents transmis</small></div></article></section>
 <section className="client-projects-section client-projects-overview"><div className="hub-title"><div><p className="eyebrow">CHANTIERS DU CLIENT</p><h3>Projets associés</h3></div><span>{projects.length}</span><button type="button" className="text-button" onClick={onAddProject}>Ajouter un projet</button></div><div className="client-project-list">{projects.map((project,index)=>{const ownPhases=phaseFor(project.id),ownTasks=tasks.filter(task=>task.project_id===project.id),value=progress(project),finance=financeFor(project);return <article className={'client-project-stack project-tone-'+index%4} key={project.id}><button className="client-project-row" onClick={()=>onOpen(project.id)}><div><b>{title(project)}</b><small>{project.data.status||'À planifier'} · {ownPhases.length} phase{ownPhases.length>1?'s':''} · {ownTasks.length} tâche{ownTasks.length>1?'s':''}</small><span className="client-project-progress"><i><em style={{width:value+'%'}}/></i>{value}%</span></div><span>Ouvrir le projet</span><ChevronRight size={18}/></button><div className="client-finance-strip" aria-label={'Résumé financier — '+title(project)}><span><small>Contrat</small><b>{money(finance.contractValue)}</b></span><span><small>Facturé</small><b>{money(finance.invoiced)}</b></span><span><small>Payé</small><b>{money(finance.paid)}</b></span><span><small>À recevoir</small><b>{money(finance.outstanding)}</b></span><span><small>Solde à facturer</small><b>{money(finance.balance)}</b></span></div><div className="client-project-actions"><button type="button" onClick={()=>onOpen(project.id)}>Tableau de bord du projet <ChevronRight size={15}/></button><button type="button" onClick={()=>onAddPhase(project.id)}><Plus size={15}/>Ajouter une phase</button></div></article>})}{!projects.length&&<p className="hub-empty">Créez le premier projet de ce client. Les devis, contrats, dépenses et tâches seront ensuite rangés dans ce projet.</p>}</div></section>
 <section className="client-profile-assets" aria-label="Note générale du dossier"><article className="client-profile-asset asset-notes"><div className="asset-heading"><span><StickyNote size={18}/></span><div><p className="eyebrow">SUIVI CLIENT</p><h3>Note générale</h3></div></div><textarea className="asset-note-editor" aria-label="Note générale du dossier" value={noteDraft} onChange={event=>setNoteDraft(event.target.value)} placeholder="Préférences, consignes et informations utiles au dossier…" maxLength={10000}/><div className="asset-note-footer"><small>{noteStatus||'Les notes sont enregistrées automatiquement.'}</small></div></article></section>
 {quick==='messages'&&<section className="client-chat-popover" aria-label="Conversation avec le client" style={{transform:'translate('+position.x+'px,'+position.y+'px)'}} onPointerMove={move} onPointerUp={()=>setDrag(null)} onPointerCancel={()=>setDrag(null)}><header onPointerDown={down}><GripVertical className="client-chat-grip" size={18}/><div><p className="eyebrow">CONVERSATION PRIVÉE</p><b>{client.data.name}</b><small>{messages.length} message{messages.length>1?'s':''} dans ce dossier</small></div><button type="button" className="client-quick-close" onPointerDown={event=>event.stopPropagation()} onClick={()=>setQuick(null)} aria-label="Fermer"><X size={16}/></button></header><div className="client-chat-list">{messages.slice(-12).map(item=><div key={item.id} className={'client-chat-message '+(item.data.sender_id===ownUserId?'own':'')}><small>{item.data.sender}</small><p>{item.data.body}</p></div>)}{!messages.length&&<p className="client-chat-empty">Commencez la conversation avec le client.</p>}</div><form onSubmit={submit}><textarea aria-label="Votre message" value={message} onChange={event=>setMessage(event.target.value)} placeholder="Écrire un message…" maxLength={10000} required/><button type="submit" disabled={sending} aria-label="Envoyer"><Send size={18}/></button></form><footer><button type="button" onClick={onMessage}>Ouvrir la messagerie complète <ChevronRight size={16}/></button></footer></section>}
 {quick==='agenda'&&<section className="client-resource-popover client-agenda-popover" aria-label="Agenda du client"><header><div><p className="eyebrow">AGENDA DU DOSSIER</p><h3>{client.data.name}</h3></div><button type="button" className="client-quick-close" onClick={()=>setQuick(null)} aria-label="Fermer"><X size={16}/></button></header><div className="client-calendar-toolbar"><button type="button" onClick={()=>setMonth(value=>new Date(value.getFullYear(),value.getMonth()-1,1))} aria-label="Mois précédent"><ChevronLeft size={18}/></button><strong>{new Intl.DateTimeFormat('fr-CA',{month:'long',year:'numeric'}).format(month)}</strong><button type="button" onClick={()=>setMonth(value=>new Date(value.getFullYear(),value.getMonth()+1,1))} aria-label="Mois suivant"><ChevronRight size={18}/></button></div><div className="client-calendar-week">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(value=><span key={value}>{value}</span>)}</div><div className="client-calendar-grid">{cells.map(value=><div className={'client-calendar-day '+(value.getMonth()===month.getMonth()?'':'outside')} key={value.toISOString()} role="button" tabIndex={0} onClick={()=>onSchedule(value.toISOString().slice(0,10))} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')onSchedule(value.toISOString().slice(0,10))}}><time>{value.getDate()}</time>{events(value).map(visit=><button type="button" key={visit.id} className="calendar-visit" style={{'--visit-color':colors[visits.indexOf(visit)%colors.length]} as React.CSSProperties} onClick={event=>{event.stopPropagation();onOpen(visit.id)}}>{title(visit)}</button>)}</div>)}</div></section>}
 <div className="client-hub-nav"><button onClick={()=>setQuick('agenda')}><CalendarDays size={17}/>Agenda <span>{visits.length}</span></button><button onClick={()=>setQuick('messages')}><MessageSquare size={17}/>Messages <span>{messages.length}</span></button><button onClick={onAddTask}><Route size={17}/>Tâches sans projet <span>{tasks.filter(task=>!task.project_id&&task.data.status!=='Validée').length}</span></button></div></section>;
}
