'use client';

import {useMemo,useState} from 'react';
import {Archive,ArchiveRestore,Download,Plus,Search,Upload,X} from 'lucide-react';
import type {Data,RecordItem} from '@/lib/model';
import {directoryCsv,duplicateGroups,previewImport,professionalsFrom,type DirectoryEntry,type DirectoryKind,type ImportPreview,type Professional} from '@/lib/directory';

type Person={id:string;name?:string;email?:string;role?:string;active?:boolean;phone?:string;avatar?:string};
type Props={clients:RecordItem[];archivedClients:RecordItem[];projects:RecordItem[];documents:RecordItem[];users:Person[];settings:Data;demo:boolean;onSaveProfessionals:(list:Professional[])=>Promise<unknown>;onOpenClient:(id:string)=>void;onOpenTeam:()=>void;onCreateClient:()=>void};
const tabs:[DirectoryKind,string][]=[['client','Clients'],['professional','Professionnels'],['employee','Employés et prestataires'],['administrator','Administrateurs']];
const PAGE=20;

/** One directory for every person the company deals with. Presence is shown only when it is really known (never simulated). */
export default function DirectoryCentre({clients,archivedClients,projects,users,settings,demo,onSaveProfessionals,onOpenClient,onOpenTeam,onCreateClient}:Props){
 const professionals=useMemo(()=>professionalsFrom(settings.directory),[settings.directory]);
 const [tab,setTab]=useState<DirectoryKind>('client'),[search,setSearch]=useState(''),[showArchived,setShowArchived]=useState(false),[page,setPage]=useState(1);
 const [draft,setDraft]=useState<Professional|null>(null),[errors,setErrors]=useState<string[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [adding,setAdding]=useState(false),[choice,setChoice]=useState('');
 const [preview,setPreview]=useState<ImportPreview|null>(null),[showDuplicates,setShowDuplicates]=useState(false);
 const photo=(client:RecordItem)=>String(client.data.photo||client.data.avatar||'')||undefined;
 const entries:DirectoryEntry[]=useMemo(()=>[
  ...[...clients.map(c=>({c,archived:false})),...archivedClients.map(c=>({c,archived:true}))].map(({c,archived})=>({id:c.id,kind:'client' as const,name:String(c.data.name||''),email:String(c.data.email||''),phone:String(c.data.phone||''),company:String(c.data.company||''),trade:'',address:String(c.data.address||''),archived,photo:photo(c),projects:projects.filter(p=>p.client_id===c.id).length,source:'record' as const})),
  ...professionals.map(p=>({id:p.id,kind:'professional' as const,name:p.name,email:p.email,phone:p.phone,company:p.company,trade:p.trade,address:p.address,archived:p.archived,source:'directory' as const})),
  ...users.filter(u=>u.role==='worker'||u.role==='admin').map(u=>({id:u.id,kind:(u.role==='admin'?'administrator':'employee') as DirectoryKind,name:String(u.name||''),email:String(u.email||''),phone:String(u.phone||''),company:'',trade:'',address:'',archived:u.active===false,photo:u.avatar||undefined,source:'profile' as const}))
 ],[clients,archivedClients,professionals,users,projects]);// eslint-disable-line react-hooks/exhaustive-deps
 const q=search.toLocaleLowerCase('fr');
 const list=entries.filter(e=>e.kind===tab&&e.archived===showArchived&&`${e.name} ${e.email} ${e.company} ${e.phone} ${e.trade}`.toLocaleLowerCase('fr').includes(q)).sort((a,b)=>a.name.localeCompare(b.name,'fr')||a.id.localeCompare(b.id));
 const pages=Math.max(1,Math.ceil(list.length/PAGE)),current=Math.min(page,pages),shown=list.slice((current-1)*PAGE,current*PAGE);
 const duplicates=useMemo(()=>duplicateGroups(entries.filter(e=>!e.archived)),[entries]);
 async function persist(next:Professional[],message:string){setBusy(true);setNotice('');try{await onSaveProfessionals(next);setNotice(demo?`${message} (démonstration : non conservé après rechargement)`:message)}catch(e){setErrors([(e as Error).message+' Vos saisies sont conservées.'])}finally{setBusy(false)}}
 async function saveDraft(){if(!draft)return;const problems=[!draft.name.trim()&&'Le nom est requis.',draft.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email)&&'Courriel invalide.'].filter(Boolean) as string[];const clash=duplicateGroups([...entries.filter(e=>e.id!==draft.id),{id:draft.id,kind:'professional',name:draft.name,email:draft.email,phone:draft.phone,company:draft.company,trade:draft.trade,address:draft.address,archived:false,source:'directory'}]).find(g=>g.entries.some(e=>e.id===draft.id));setErrors(problems);if(problems.length)return;if(clash&&!window.confirm(`Doublon possible (${clash.reasons.join(', ')}) avec : ${clash.entries.filter(e=>e.id!==draft.id).map(e=>e.name).join(', ')}. Enregistrer quand même ?`))return;await persist([{...draft,name:draft.name.trim(),email:draft.email.trim().toLowerCase()},...professionals.filter(p=>p.id!==draft.id)],'Professionnel enregistré.');setDraft(null)}
 function download(rows:DirectoryEntry[]){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([directoryCsv(rows)],{type:'text/csv;charset=utf-8'}));a.download=`yello-pro-repertoire-${tab}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <section className="panel directory-centre">
  <div className="module-section-heading"><div><h2>Répertoire</h2><p>Clients, professionnels sans accès logiciel, employés et administrateurs. Créer un contact n’envoie aucune invitation.</p></div><div className="module-actions"><button className="btn secondary" onClick={()=>download(list)}><Download size={15}/>Exporter</button>{tab==='professional'&&<><label className="btn secondary upload-button"><Upload size={15}/>Importer CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>2_000_000){setErrors(['Fichier trop volumineux (2 Mo maximum).']);return}setPreview(previewImport(await file.text(),entries))}}/></label></>}<button className="btn primary" onClick={()=>{setChoice('');setAdding(true)}}><Plus size={15}/>Ajouter un contact</button>{(tab==='employee'||tab==='administrator')&&<button className="btn secondary" onClick={onOpenTeam}>Gérer les accès</button>}</div></div>
  <div className="vendor-tabs" role="tablist" aria-label="Types de contacts">{tabs.map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>{setTab(id);setPage(1);setDraft(null)}}>{label}<span>{entries.filter(e=>e.kind===id&&!e.archived).length}</span></button>)}</div>
  <div className="module-toolbar"><label className="module-search"><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Nom, courriel, entreprise, téléphone…" aria-label="Rechercher dans le répertoire"/></label><label className="note-visibility"><input type="checkbox" checked={showArchived} onChange={e=>{setShowArchived(e.target.checked);setPage(1)}}/>Afficher les archivés</label>{duplicates.length>0&&<button className="btn ghost" aria-expanded={showDuplicates} onClick={()=>setShowDuplicates(x=>!x)}>Doublons possibles ({duplicates.length})</button>}</div>
  {adding&&<div className="filter-drawer" role="dialog" aria-modal="true" aria-label="Ajouter un contact" onKeyDown={e=>{if(e.key==='Escape')setAdding(false)}}><h3>Quel type de contact ?</h3><div className="contact-types" role="radiogroup">{([['admin','Administrateur','Accès complet à l’administration. Se crée par invitation depuis Équipe et accès.',false],['manager','Gestionnaire de projet','Rôle non disponible dans Yello Pro : les accès se donnent projet par projet aux prestataires.',true],['client','Client','Fiche client et accès à son espace (invitation séparée, jamais automatique).',false],['worker','Employé de terrain / prestataire','Accès aux projets assignés, tâches, temps, journal et fichiers. Invitation depuis Équipe et accès.',false],['professional','Sous-traitant, fournisseur ou professionnel','Contact sans accès logiciel, utilisé pour les demandes de prix et achats.',false]] as const).map(([id,label,help,disabled])=><label key={id} className={`contact-type${disabled?' disabled':''}`}><input type="radio" name="contact-type" disabled={disabled} checked={choice===id} onChange={()=>setChoice(id)}/><span><b>{label}</b><small>{help}</small></span></label>)}</div><div className="module-actions"><button className="btn secondary" onClick={()=>setAdding(false)}>Annuler</button><button className="btn primary" disabled={!choice} onClick={()=>{setAdding(false);if(choice==='client')onCreateClient();else if(choice==='professional'){setTab('professional');setErrors([]);setDraft({id:crypto.randomUUID(),name:'',email:'',phone:'',company:'',trade:'',address:'',notes:'',archived:false})}else onOpenTeam()}}>Confirmer</button></div></div>}
  {notice&&<p role="status" className="settings-saved">{notice}</p>}
  {errors.length>0&&<ul className="error vendor-errors" role="alert">{errors.map(x=><li key={x}>{x}</li>)}</ul>}
  {showDuplicates&&<div className="directory-duplicates"><p className="muted">Rien n’est fusionné automatiquement : vérifiez chaque groupe et archivez l’entrée en trop.</p>{duplicates.map((g,i)=><div key={i}><b>{g.reasons.join(' · ')}</b><ul>{g.entries.map(e=><li key={e.id}>{e.name||'Sans nom'} — {tabs.find(t=>t[0]===e.kind)?.[1]} {e.email&&`· ${e.email}`} {e.phone&&`· ${e.phone}`}</li>)}</ul></div>)}</div>}
  {preview&&<div className="directory-import" role="dialog" aria-label="Aperçu de l’import"><h3>Aperçu de l’import</h3><p>{preview.valid.length} ligne(s) valides · {preview.invalid.length} invalide(s) · {preview.duplicates.length} doublon(s) ignoré(s).</p>{preview.invalid.length>0&&<ul className="error vendor-errors">{preview.invalid.slice(0,20).map(x=><li key={x.line}>Ligne {x.line} : {x.errors.join(' ')}</li>)}</ul>}{preview.duplicates.length>0&&<ul className="muted">{preview.duplicates.slice(0,20).map(x=><li key={x.line}>Ligne {x.line} : déjà présent ({x.match})</li>)}</ul>}<div className="module-actions"><button className="btn secondary" onClick={()=>setPreview(null)}>Annuler</button><button className="btn primary" disabled={!preview.valid.length||busy} onClick={()=>void persist([...preview.valid.map(v=>({...v,id:crypto.randomUUID(),archived:false})),...professionals],`${preview.valid.length} professionnel(s) importé(s).`).then(()=>setPreview(null))}>Importer les {preview.valid.length} ligne(s) valides</button></div></div>}
  {draft&&<form className="vendor-form" onSubmit={e=>{e.preventDefault();void saveDraft()}} aria-label="Professionnel"><label>Nom<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Entreprise<input value={draft.company} onChange={e=>setDraft({...draft,company:e.target.value})}/></label><label>Métier<input value={draft.trade} onChange={e=>setDraft({...draft,trade:e.target.value})} placeholder="Électricien, fournisseur de bois…"/></label><label>Courriel<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Téléphone<input type="tel" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Adresse<input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label className="wide">Notes internes<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="module-actions wide"><button className="btn primary" disabled={busy}>Enregistrer</button><button type="button" className="btn ghost" onClick={()=>setDraft(null)}><X size={15}/>Annuler</button></div></form>}
  {shown.length?<div className="vendor-table" role="region" aria-label="Contacts" tabIndex={0}><table><thead><tr><th>Nom</th><th>Courriel</th><th>Téléphone</th><th>{tab==='client'?'Projets':tab==='professional'?'Entreprise · métier':'Statut du compte'}</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{shown.map(e=><tr key={e.id}><th scope="row"><span className="directory-name">{e.photo?<img src={e.photo} alt=""/>:<span className="avatar-initials" aria-hidden="true">{e.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'?'}</span>}{e.name||'Sans nom'}</span></th><td>{e.email?<a href={`mailto:${e.email}`}>{e.email}</a>:'—'}</td><td>{e.phone?<a href={`tel:${e.phone}`}>{e.phone}</a>:'—'}</td><td>{tab==='client'?e.projects:tab==='professional'?[e.company,e.trade].filter(Boolean).join(' · ')||'—':e.archived?'Désactivé':'Actif'}</td><td className="vendor-actions">{e.kind==='client'&&<button className="btn ghost" onClick={()=>onOpenClient(e.id)}>Ouvrir la fiche</button>}{e.kind==='professional'&&<><button className="btn ghost" onClick={()=>{const p=professionals.find(x=>x.id===e.id);if(p){setErrors([]);setDraft(structuredClone(p))}}}>Modifier</button><button className="icon-button" aria-label={e.archived?`Restaurer ${e.name}`:`Archiver ${e.name}`} disabled={busy} onClick={()=>void persist(professionals.map(p=>p.id===e.id?{...p,archived:!p.archived}:p),e.archived?'Contact restauré.':'Contact archivé. Il reste consultable dans les archivés.')}>{e.archived?<ArchiveRestore size={15}/>:<Archive size={15}/>}</button></>}{(e.kind==='employee'||e.kind==='administrator')&&<button className="btn ghost" onClick={onOpenTeam}>Accès</button>}</td></tr>)}</tbody></table></div>:<div className="portal-empty"><p>{search?'Aucun résultat pour cette recherche.':showArchived?'Aucun contact archivé.':'Aucun contact dans cette catégorie.'}</p></div>}
  <nav className="projects-pagination" aria-label="Pages du répertoire"><button type="button" disabled={current===1} onClick={()=>setPage(current-1)}>Précédent</button><span>{list.length?`${(current-1)*PAGE+1} à ${Math.min(list.length,current*PAGE)} sur ${list.length}`:'0 résultat'}</span><button type="button" disabled={current===pages} onClick={()=>setPage(current+1)}>Suivant</button></nav>
  {tab==='client'&&<p className="muted">L’archivage d’un client se fait depuis sa fiche (corbeille restaurable). La présence en ligne n’est pas affichée : aucune source fiable ne la fournit.</p>}
 </section>;
}
