'use client';
import {useRef,useState} from 'react';
import {PDFDocument,rgb} from 'pdf-lib';
type Point={x:number;y:number};
export type Notebook={strokes:Point[][];text:string};
export default function HandwrittenNotebook({value,onChange}:{value?:Notebook;onChange:(value:Notebook)=>void}){
 const strokes=value?.strokes||[],text=value?.text||'';
 const [active,setActive]=useState<Point[]>([]),[error,setError]=useState('');
 const current=useRef<Point[]>([]),pointer=useRef<number|null>(null);
 const point=(e:React.PointerEvent<SVGSVGElement>)=>{const b=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(800,(e.clientX-b.left)/b.width*800)),y:Math.max(0,Math.min(500,(e.clientY-b.top)/b.height*500))}};
 const finish=()=>{if(current.current.length){onChange({text,strokes:[...strokes,current.current]});current.current=[];setActive([])}pointer.current=null};
 async function download(){try{setError('');const pdf=await PDFDocument.create();const page=pdf.addPage([842,595]);for(const stroke of strokes){if(stroke.length===1)page.drawCircle({x:stroke[0].x+21,y:550-stroke[0].y,size:1.2,color:rgb(.12,.22,.17)});for(let i=1;i<stroke.length;i++)page.drawLine({start:{x:stroke[i-1].x+21,y:550-stroke[i-1].y},end:{x:stroke[i].x+21,y:550-stroke[i].y},thickness:2,color:rgb(.12,.22,.17)})}const bytes=await pdf.save();const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/pdf'}));const link=document.createElement('a');link.href=url;link.download='carnet-croquis.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError('Export impossible. Vos tracés restent dans le carnet.')}}
 return <details className="handwritten-notebook"><summary>Carnet manuscrit · doigt, souris ou stylet</summary><p>Écrivez ou dessinez dans le cadre. Les tracés sont enregistrés avec le brouillon du document.</p><svg viewBox="0 0 800 500" role="img" aria-label="Carnet de notes et croquis" onPointerDown={e=>{if(pointer.current!==null||strokes.length>=500)return;pointer.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);current.current=[point(e)];setActive(current.current)}} onPointerMove={e=>{if(pointer.current!==e.pointerId||current.current.length>=5000)return;current.current=[...current.current,point(e)];setActive(current.current)}} onPointerUp={finish} onPointerCancel={finish}>{[...strokes,active].map((stroke,index)=><polyline key={index} points={stroke.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#264e3a" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>)}</svg><div className="button-row"><button type="button" className="btn secondary" disabled={!strokes.length} onClick={()=>onChange({text,strokes:strokes.slice(0,-1)})}>Annuler le dernier trait</button><button type="button" className="btn secondary" disabled={!strokes.length} onClick={download}>Télécharger le croquis PDF</button></div><label>Transcription et mesures du croquis<textarea value={text} onChange={e=>onChange({strokes,text:e.target.value})} placeholder="Décrivez les pièces, dimensions et travaux à reprendre dans le devis…"/></label><p className="muted">La transcription manuscrite et la conversion automatique en plan coté restent à compléter. Les mesures et les tracés doivent être vérifiés avant utilisation.</p>{error&&<p role="alert">{error}</p>}</details>;
}
