 'use client';
import {useEffect,useState} from 'react';
import PlanEditor from './plan-editor';
import type {Plan} from '@/lib/plan';
type Share={id:string;plan:Plan;version:number;created_at:string;expires_at:string};
export default function PlanInvitations({id,email='',demo=false}:{id:string;email?:string;demo?:boolean}){
 const [shares,setShares]=useState<Share[]>([]),[link,setLink]=useState(''),[recipient,setRecipient]=useState(email),[cc,setCc]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[opened,setOpened]=useState<string|null>(null);
 async function load(){if(demo)return;const r=await fetch('/api/plans/share?id='+encodeURIComponent(id));const d=await r.json();if(!r.ok)throw Error(d.error);setShares(d.shares)}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[id,demo]);
 async function create(){setBusy(true);try{const r=await fetch('/api/plans/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)throw Error(d.error);setLink(location.origin+'/plans/'+d.token);await load();setMessage('Invitation créée. Copiez le lien ou préparez le courriel ci-dessous.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel"><div className="panel-title"><h2>Plans et préférences du client</h2></div><div className="detail-body"><p>Partagez le plan validé et les ambiances, sans aucun prix. Les dimensions restent protégées.</p><button type="button" className="btn primary" disabled={demo||busy} onClick={create}>Créer une invitation</button>{link&&<><label>Courriel du client<input type="email" value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label>Copie (facultative)<input type="text" value={cc} onChange={e=>setCc(e.target.value)} placeholder="architecte@exemple.com, equipe@exemple.com"/></label><label>Lien personnel<input readOnly value={link}/></label><div className="button-row"><button type="button" className="btn secondary" onClick={()=>navigator.clipboard.writeText(link).then(()=>setMessage('Lien copié.')).catch(()=>setMessage('Sélectionnez le lien puis copiez-le.'))}>Copier le lien</button><a className="btn secondary" href={`mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent('Yello Pro — votre plan et vos ambiances')}&cc=${encodeURIComponent(cc)}&body=${encodeURIComponent('Bonjour,\n\nDécouvrez vos plans 2D et 3D et personnalisez les couleurs et matériaux :\n'+link+'\n\nCe lien personnel est valable 30 jours.\nYello Pro')}`}>Préparer le courriel</a></div><p className="muted">Votre messagerie s’ouvre avec l’invitation. Vous confirmez vous-même l’envoi.</p></>}{message&&<p role="status">{message}</p>}{shares.map(s=><div key={s.id}><p>Invitation du {new Date(s.created_at).toLocaleDateString('fr-CA')} · {new Date(s.expires_at).getTime()>Date.now()?'Active':'Expirée'} · {s.version>1?'Choix personnalisés par le client':'Choix initiaux'}</p><div className="button-row"><button type="button" className="btn secondary" onClick={()=>setOpened(opened===s.id?null:s.id)}>Consulter les préférences</button><button type="button" className="btn ghost" disabled={busy||new Date(s.expires_at).getTime()<=Date.now()} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/plans/share',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:s.id})});if(!r.ok)throw Error('Révocation impossible.');await load();setMessage('Accès révoqué.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Révoquer l’accès</button></div>{opened===s.id&&<PlanEditor value={s.plan} onChange={()=>{}} client/>}</div>)}</div></section>
}
