'use client';
import {useEffect,useRef,useState} from 'react';
import type {Plan} from '@/lib/plan';
import {bounds} from '@/lib/plan';
export default function PlanScene({plan,roof=false,top=false}:{plan:Plan;roof?:boolean;top?:boolean}){
 const host=useRef<HTMLDivElement>(null);const [error,setError]=useState('');
 useEffect(()=>{let dispose=()=>{};let cancelled=false;(async()=>{try{const T=await import('three');const {OrbitControls}=await import('three/addons/controls/OrbitControls.js');if(cancelled||!host.current)return;const el=host.current;const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;el.appendChild(renderer.domElement);const scene=new T.Scene();scene.background=new T.Color('#e8e9e3');const {w,h}=bounds(plan);const size=Math.max(w,h);const camera=new T.PerspectiveCamera(40,1,.05,1000);camera.position.set(w/2+size,top?size*2:size,h/2+(top?.01:size));const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(w/2,0,h/2);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;scene.add(new T.HemisphereLight('#fff9ef','#8b9781',2.8));const sun=new T.DirectionalLight('#fff1d2',4);sun.position.set(w+6,15,-4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-size*2;sun.shadow.camera.right=size*2;sun.shadow.camera.top=size*2;sun.shadow.camera.bottom=-size*2;scene.add(sun);
 function box(x:number,y:number,z:number,a:number,b:number,c:number,color:string,opacity=1){const mesh=new T.Mesh(new T.BoxGeometry(a,b,c),new T.MeshStandardMaterial({color,roughness:.72,transparent:opacity<1,opacity}));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);return mesh;}
 box(w/2,-.2,h/2,w+4,.15,h+4,'#d4d7ca');
 for(const r of plan.rooms.filter(r=>r.phase!=='remove')){const x=r.x,z=r.y,l=r.length,d=r.width,H=r.height;box(x+l/2,0,z+d/2,l,.12,d,r.floor);if(!r.floorFinish||r.floorFinish==='wood'){for(let p=.18;p<l;p+=.18)box(x+p,.066,z+d/2,.008,.003,d,'#8d7d68',.25);}else if(r.floorFinish==='tile'){for(let p=.6;p<l;p+=.6)box(x+p,.066,z+d/2,.012,.003,d,'#dedbd2');for(let p=.6;p<d;p+=.6)box(x+l/2,.066,z+p,l,.003,.012,'#dedbd2');}
 // Rear wall with an optional centred window, and side walls with a door opening.
 if(r.window){const a=Math.min(1.4,l*.5);box(x+(l-a)/4,H/2,z,(l-a)/2,H,.12,r.wall);box(x+l-(l-a)/4,H/2,z,(l-a)/2,H,.12,r.wall);box(x+l/2,.45,z,a,.9,.12,r.wall);box(x+l/2,(H+2)/2,z,a,Math.max(.1,H-2),.12,r.wall);box(x+l/2,1.45,z,a,1.1,.035,'#a0cad8',.4);}else box(x+l/2,H/2,z,l,H,.12,r.wall);
 box(x,H/2,z+d/2,.12,H,d,r.wall);if(r.door){const a=Math.min(.9,d*.4);box(x+l,H/2,z+(d-a)/2,.12,H,d-a,r.wall);box(x+l,(H+2)/2,z+d-a/2,.12,Math.max(.1,H-2),a,r.wall);}else box(x+l,H/2,z+d/2,.12,H,d,r.wall);
 if(r.wallFinish==='brick'&&!r.window){for(let row=.16;row<H;row+=.18){box(x+l/2,row,z+.066,l,.012,.005,'#a59d90');for(let col=(Math.round(row/.18)%2)*.2;col<l;col+=.4)box(x+col,row-.08,z+.067,.012,.16,.005,'#a59d90');}}
 if(roof)box(x+l/2,H,z+d/2,l+.2,.15,d+.2,'#444a45');
 const cx=x+l/2,cz=z+d/2;
 if(r.furniture==='living'){box(cx,.3,cz,Math.min(2.2,l*.7),.6,.85,'#e7dfce');box(cx,.7,cz-.35,Math.min(2.2,l*.7),.6,.16,'#d3c8b5');box(cx,.25,cz+1,Math.min(1,l*.4),.5,.55,'#806b50');}
 if(r.furniture==='bedroom'){box(cx,.25,cz,Math.min(1.6,l*.7),.5,Math.min(2,d*.65),'#a88d70');box(cx,.55,cz,Math.min(1.55,l*.68),.2,Math.min(1.95,d*.63),'#ede8dd');box(cx,.7,cz-.6,1,.15,.4,'#899984');}
 if(r.furniture==='kitchen'){box(cx,.45,z+.4,l*.8,.9,.65,'#d4c8b5');box(cx,.94,z+.4,l*.82,.08,.72,'#faf8ed');box(cx,.45,cz,l*.45,.9,.8,'#8d785b');box(cx,.94,cz,l*.48,.08,.85,'#e9e7de');}
 if(r.furniture==='bath'){box(cx,.3,cz,Math.min(1.6,l*.7),.6,.7,'#fcfcf8');box(x+.4,.45,z+.4,.6,.9,.6,'#b2a38c');}
 }
 for(const element of plan.elements||[]){if(element.phase==='remove')continue;const color=element.kind==='window'?'#a0cad8':element.kind==='door'?'#a9855e':element.kind==='wall'?'#d8d4ca':element.kind==='counter'||element.kind==='island'?'#816e58':element.kind==='stairs'?'#d8d0c0':'#a1b09f';const height=element.kind==='wall'?Math.max(2.1,element.height):element.kind==='door'?2.05:element.kind==='window'?1.15:element.kind==='note'?.04:Math.max(.35,element.height);box(element.x+element.length/2,height/2,element.y+element.width/2,element.length,height,Math.max(.08,element.width),color,element.kind==='window'?.45:1);if(element.kind==='stairs'){for(let step=.15;step<element.width;step+=.15)box(element.x+element.length/2,.08,element.y+step,element.length,.035,.02,'#8a806f');}}
 const resize=()=>{const a=el.clientWidth,b=el.clientHeight;renderer.setSize(a,b);camera.aspect=a/Math.max(1,b);const distance=size*1.45/Math.min(1,camera.aspect);camera.position.set(w/2+(top?0:distance),top?distance*1.65:distance,h/2+(top?.01:distance));camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();let raf=0;const draw=()=>{controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(draw)};draw();dispose=()=>{cancelAnimationFrame(raf);observer.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const m=o.material;(Array.isArray(m)?m:[m]).forEach(v=>v.dispose())}});renderer.dispose();renderer.domElement.remove()};}catch{setError('La 3D nécessite WebGL sur cet appareil. Le plan 2D reste disponible.')}})();return()=>{cancelled=true;dispose()}},[plan,roof,top]);
 return <div className="plan-scene" ref={host} aria-label="Maquette 3D interactive">{error&&<p role="alert">{error}</p>}<button type="button" className="btn secondary" style={{position:"absolute",bottom:12,right:12}} onClick={()=>{const canvas=host.current?.querySelector("canvas");if(!canvas)return;const a=document.createElement("a");a.download="yello-pro-maquette-3d.png";a.href=canvas.toDataURL("image/png");a.click()}}>Télécharger la vue</button></div>;
}
