'use client';

import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Download,FolderKanban,LayoutGrid,List,Map as MapIcon,MapPin,MoreHorizontal,Search,SlidersHorizontal,X} from 'lucide-react';
import type {RecordItem} from '@/lib/model';
import {csvCell,datePresets,inRange,presetRange,resultLabel,type DateFilter,type DatePreset} from '@/lib/project-filters';
import type {Point} from '@/lib/geo';
import ProjectMap from './project-map';

type Props={projects:RecordItem[];clients:RecordItem[];tasks:RecordItem[];onOpen:(id:string)=>void;onEdit?:(project:RecordItem)=>void;onLocate?:(project:RecordItem,point:Point&{label:string})=>Promise<unknown>;onBulkStatus?:(projects:RecordItem[],status:string)=>Promise<unknown>;demo?:boolean};
const stages=['Tous','À soumissionner','Soumission envoyée','Soumission signée','En construction','Complété','Archivés'];
function stage(project:RecordItem){if(project.data.archived||project.data.status==='Archivé')return 'Archivés';return ({'Planifié':'À soumissionner','En cours':'En construction','Terminé':'Complété'} as Record<string,string>)[project.data.status]||project.data.status||'À soumissionner'}
const dateFields=[['created','Création'],['start','Début des travaux'],['end','Échéance / fin']] as const;
type DateKey=typeof dateFields[number][0];
type Filters={search:string;status:string;clientId:string;assignee:string;sort:string;view:'cards'|'list'|'map';page:number;dates:Record<DateKey,DateFilter>};
const emptyDates=():Record<DateKey,DateFilter>=>({created:{preset:'',from:'',to:''},start:{preset:'',from:'',to:''},end:{preset:'',from:'',to:''}});
const storageKey='yello-pro-projects-explorer';
const PAGE=24;
function restore():Filters{const base:Filters={search:'',status:'Tous',clientId:'',assignee:'',sort:'updated',view:'cards',page:1,dates:emptyDates()};try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');return saved&&typeof saved==='object'?{...base,...saved,dates:{...emptyDates(),...saved.dates}}:base}catch{return base}}
const today=()=>new Date().toISOString().slice(0,10);

export default function ProjectsExplorer({projects,clients,tasks,onOpen,onEdit,onLocate,onBulkStatus,demo=false}:Props){
 const root=useRef<HTMLElement>(null);
 const [filters,setFilters]=useState<Filters>(restore);
 const {search,status,clientId,assignee,sort,view,dates}=filters;
 const set=(patch:Partial<Filters>)=>setFilters(old=>({...old,page:'page' in patch?patch.page!:1,...patch}));
 useEffect(()=>{try{sessionStorage.setItem(storageKey,JSON.stringify(filters))}catch{}},[filters]);
 useEffect(()=>{const close=(event:PointerEvent|KeyboardEvent)=>{root.current?.querySelectorAll<HTMLDetailsElement>('details[open].project-row-menu').forEach(menu=>{if(event instanceof KeyboardEvent?event.key==='Escape':!menu.contains(event.target as Node)){menu.open=false;if(event instanceof KeyboardEvent)menu.querySelector('summary')?.focus();}})};document.addEventListener('pointerdown',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',close)}},[]);
 const [drawer,setDrawer]=useState<Record<DateKey,DateFilter>|null>(null);
 const [selection,setSelection]=useState<string[]>([]),[bulk,setBulk]=useState(''),[bulkBusy,setBulkBusy]=useState(false),[bulkMessage,setBulkMessage]=useState('');
 const clientName=(project:RecordItem)=>clients.find(client=>client.id===project.client_id)?.data.name||'Client à préciser';
 const assigned=(project:RecordItem)=>String(project.data.assignee||project.data.manager||'');
 const people=Array.from(new Set(projects.map(assigned).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'fr'));
 const ranges=Object.fromEntries(dateFields.map(([key])=>[key,presetRange(dates[key].preset,today(),dates[key])])) as Record<DateKey,{from:string;to:string}>;
 const dateValue=(project:RecordItem,key:DateKey)=>key==='created'?project.created_at:project.data[key];
 const activeDates=dateFields.filter(([key])=>dates[key].preset).length;
 const filtered=projects.filter(project=>(status==='Tous'?stage(project)!=='Archivés':stage(project)===status)&&(!clientId||project.client_id===clientId)&&(!assignee||assigned(project)===assignee)&&dateFields.every(([key])=>inRange(dateValue(project,key),ranges[key]))&&[project.data.title,project.data.address,project.data.number,clientName(project)].join(' ').toLocaleLowerCase('fr').includes(search.toLocaleLowerCase('fr'))).sort((a,b)=>(sort==='name'?String(a.data.title||'').localeCompare(String(b.data.title||''),'fr'):sort==='end'?String(a.data.end||'9999').localeCompare(String(b.data.end||'9999')):String(b.updated_at||'').localeCompare(String(a.updated_at||'')))||a.id.localeCompare(b.id));
 const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE));const activePage=Math.min(filters.page,pageCount);const visible=filtered.slice((activePage-1)*PAGE,activePage*PAGE);
 useEffect(()=>{setSelection(old=>old.filter(id=>filtered.some(p=>p.id===id)))},[filtered.length]);// eslint-disable-line react-hooks/exhaustive-deps
 const progress=(project:RecordItem)=>{const related=tasks.filter(task=>task.project_id===project.id);const done=related.filter(task=>task.data.status==='Validée').length;return {done,total:related.length,percent:related.length?Math.round(done/related.length*100):0}};
 const toggle=(id:string)=>setSelection(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 const chosen=filtered.filter(p=>selection.includes(p.id));
 function exportCsv(rows:RecordItem[]){const header=['Référence','Projet','Client','Adresse','Étape','Responsable','Créé le','Début','Échéance','Tâches terminées'];const lines=rows.map(p=>{const pr=progress(p);return [p.data.number||'',p.data.title||'',clientName(p),p.data.address||'',stage(p),assigned(p),p.created_at.slice(0,10),p.data.start||'',p.data.end||'',`${pr.done}/${pr.total}`]});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['﻿'+[header,...lines].map(l=>l.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download='yello-pro-projets.csv';a.click();URL.revokeObjectURL(a.href)}
 async function applyBulk(){if(!onBulkStatus||!bulk||!chosen.length)return;if(!window.confirm(`Passer ${chosen.length} projet(s) au statut « ${bulk} » ? Aucun document n’est envoyé.`))return;setBulkBusy(true);setBulkMessage('');try{await onBulkStatus(chosen,bulk);setBulkMessage(`${chosen.length} projet(s) mis à jour.`);setSelection([]);setBulk('')}catch(e){setBulkMessage((e as Error).message)}finally{setBulkBusy(false)}}
 const menu=(project:RecordItem)=><details className="project-row-menu"><summary aria-label={`Actions pour ${project.data.title||'le projet'}`}><MoreHorizontal size={18}/></summary><div><button type="button" onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');onOpen(project.id)}}>Ouvrir le dossier</button>{onEdit&&<button type="button" onClick={event=>{event.currentTarget.closest('details')?.removeAttribute('open');onEdit(project)}}>Modifier le projet</button>}</div></details>;
 const check=(project:RecordItem)=><label className="project-select"><input type="checkbox" checked={selection.includes(project.id)} onChange={()=>toggle(project.id)} aria-label={`Sélectionner ${project.data.title||'le projet'}`}/></label>;
 return <section ref={root} className="panel projects-explorer">
  <header className="projects-explorer-toolbar"><label className="search-input"><Search size={16}/><input aria-label="Rechercher un projet, client ou adresse" placeholder="Projet, client, adresse…" value={search} onChange={event=>set({search:event.target.value})}/>{search&&<button type="button" className="icon-button" aria-label="Effacer la recherche" onClick={()=>set({search:''})}><X size={14}/></button>}</label><div className="projects-view-switch" role="group" aria-label="Affichage des projets"><button type="button" aria-pressed={view==='list'} onClick={()=>set({view:'list',page:activePage})}><List size={16}/>Liste</button><button type="button" aria-pressed={view==='cards'} onClick={()=>set({view:'cards',page:activePage})}><LayoutGrid size={16}/>Cartes</button><button type="button" aria-pressed={view==='map'} onClick={()=>set({view:'map',page:activePage})}><MapIcon size={16}/>Carte</button></div></header>
  <div className="projects-stage-tabs" role="group" aria-label="Étape des projets">{stages.map(value=><button type="button" key={value} aria-pressed={value===status} onClick={()=>set({status:value})}>{value}<span>{projects.filter(project=>value==='Tous'?stage(project)!=='Archivés':stage(project)===value).length}</span></button>)}</div>
  <div className="projects-explorer-filters"><label>Client<select value={clientId} onChange={event=>set({clientId:event.target.value})}><option value="">Tous les clients</option>{clients.map(client=><option key={client.id} value={client.id}>{client.data.name}</option>)}</select></label><label>Responsable<select value={assignee} onChange={event=>set({assignee:event.target.value})}><option value="">Tous les responsables</option>{people.map(person=><option key={person}>{person}</option>)}</select></label><label>Trier par<select value={sort} onChange={event=>set({sort:event.target.value})}><option value="updated">Dernière modification</option><option value="name">Nom du projet</option><option value="end">Échéance</option></select></label><button type="button" className="btn secondary" aria-expanded={!!drawer} onClick={()=>setDrawer(structuredClone(dates))}><SlidersHorizontal size={15}/>Plus de filtres{activeDates?<span className="badge">{activeDates}</span>:null}</button><span role="status">{filtered.length} projet{filtered.length!==1?'s':''}</span></div>
  {drawer&&<div className="filter-drawer" role="dialog" aria-label="Filtres de dates" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();setDrawer(null)}}}>
   <h3>Filtres de dates</h3>
   {dateFields.map(([key,label])=><fieldset key={key}><legend>{label}</legend><select aria-label={`Période — ${label}`} value={drawer[key].preset} onChange={e=>setDrawer({...drawer,[key]:{...drawer[key],preset:e.target.value as DatePreset|''}})}><option value="">Toutes les dates</option>{datePresets.map(p=><option key={p}>{p}</option>)}</select>{drawer[key].preset==='Dates choisies'&&<div className="filter-range"><label>Du<input type="date" value={drawer[key].from} onChange={e=>setDrawer({...drawer,[key]:{...drawer[key],from:e.target.value}})}/></label><label>Au<input type="date" value={drawer[key].to} onChange={e=>setDrawer({...drawer,[key]:{...drawer[key],to:e.target.value}})}/></label></div>}</fieldset>)}
   <div className="module-actions"><button type="button" className="btn ghost" onClick={()=>setDrawer(emptyDates())}>Tout réinitialiser</button><button type="button" className="btn secondary" onClick={()=>setDrawer(null)}>Annuler</button><button type="button" className="btn primary" disabled={dateFields.some(([key])=>drawer[key].preset==='Dates choisies'&&drawer[key].from>drawer[key].to&&!!drawer[key].to)} onClick={()=>{set({dates:drawer});setDrawer(null)}}>Appliquer</button></div>
  </div>}
  {view!=='map'&&(chosen.length>0||filtered.length>0)&&<div className="projects-bulk" role="group" aria-label="Actions groupées"><label className="note-visibility"><input type="checkbox" checked={visible.length>0&&visible.every(p=>selection.includes(p.id))} ref={el=>{if(el)el.indeterminate=visible.some(p=>selection.includes(p.id))&&!visible.every(p=>selection.includes(p.id))}} onChange={e=>setSelection(old=>e.target.checked?[...new Set([...old,...visible.map(p=>p.id)])]:old.filter(id=>!visible.some(p=>p.id===id)))}/>Page</label><span>{chosen.length?`${chosen.length} sélectionné(s)`:'Aucune sélection'}</span><button type="button" className="btn ghost" onClick={()=>exportCsv(chosen.length?chosen:filtered)}><Download size={15}/>Exporter {chosen.length?'la sélection':'le périmètre filtré'}</button>{onBulkStatus&&chosen.length>0&&<><select aria-label="Nouveau statut" value={bulk} onChange={e=>setBulk(e.target.value)}><option value="">Changer le statut…</option>{['À soumissionner','Soumission envoyée','Soumission signée','En construction','Complété','En pause','Archivé'].map(x=><option key={x}>{x}</option>)}</select><button type="button" className="btn secondary" disabled={!bulk||bulkBusy} onClick={()=>void applyBulk()}>{bulkBusy?'Mise à jour…':'Appliquer'}</button></>}{bulkMessage&&<small role="status">{bulkMessage}</small>}</div>}
  {view==='map'?<ProjectMap projects={filtered} clientName={clientName} stage={stage} onOpen={onOpen} onLocate={onLocate} demo={demo}/>:view==='cards'?<div className="project-cards">{visible.map(project=>{const p=progress(project);return <article className="project-card" key={project.id}><div className="project-card-top">{check(project)}<FolderKanban size={22}/><span className="badge">{stage(project)}</span>{menu(project)}</div><button type="button" className="project-card-open" onClick={()=>onOpen(project.id)}><h2>{project.data.title||'Projet sans titre'}</h2><p>{clientName(project)}</p><p><MapPin size={14}/>{project.data.address||'Adresse à préciser'}</p><div className="progress"><span style={{width:p.percent+'%'}}/></div><small>{p.done}/{p.total} tâches terminées</small><footer><span>{project.data.end||'Échéance à définir'}</span><ArrowUpRight size={18}/></footer></button></article>})}</div>:<div className="projects-list">{visible.map(project=>{const p=progress(project);return <article className="projects-list-row" key={project.id}>{check(project)}<button type="button" onClick={()=>onOpen(project.id)}><div><small>{project.data.number||'Projet'}</small><h3>{project.data.title||'Projet sans titre'}</h3><p>{clientName(project)} · {project.data.address||'Adresse à préciser'}</p></div><span className="badge">{stage(project)}</span><span className="projects-list-progress">{p.percent}%<small>{p.done}/{p.total} tâches</small></span><span className="projects-list-date">{project.data.end||'Échéance à définir'}</span><ArrowUpRight size={16}/></button>{menu(project)}</article>})}</div>}
  {view!=='map'&&<nav className="projects-pagination" aria-label="Pages des projets"><button type="button" disabled={activePage===1} onClick={()=>set({page:activePage-1})}>Précédent</button><span>{resultLabel(filtered.length,activePage,PAGE)} · page {activePage} sur {pageCount}</span><button type="button" disabled={activePage===pageCount} onClick={()=>set({page:activePage+1})}>Suivant</button></nav>}
  {!filtered.length&&<div className="empty"><p>Aucun résultat.</p><p>Aucun projet ne correspond aux filtres sélectionnés.</p><button type="button" className="btn ghost" onClick={()=>setFilters(old=>({...old,search:'',status:'Tous',clientId:'',assignee:'',dates:emptyDates(),page:1}))}>Réinitialiser les filtres</button></div>}
 </section>;
}
