 'use client';
import {useEffect,useState} from 'react';
import PlanEditor from './plan-editor';
import {planSchema,type Plan} from '@/lib/plan';
export default function SharedPlan({token}:{token:string}){
 const [plan,setPlan]=useState<Plan|null>(null),[version,setVersion]=useState(0),[message,setMessage]=useState('Chargement du projet…'),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState<Plan|null>(null);const key='yello-pro-client-plan-'+token;
 useEffect(()=>{fetch('/api/plans/view?token='+token).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setPlan(d.plan);setVersion(d.version);setMessage('Explorez votre plan et personnalisez votre ambiance.');try{const raw=localStorage.getItem(key);if(raw){const local=JSON.parse(raw);if(local.version===d.version&&planSchema.safeParse(local.plan).success)setRecovery(local.plan);else localStorage.removeItem(key)}}catch{}}).catch(e=>setMessage(e.message));},[token,key]);
 function change(p:Plan){setPlan(p);try{localStorage.setItem(key,JSON.stringify({plan:p,version}));setMessage('Modifications conservées sur cet appareil. Enregistrez pour les transmettre à Yello Pro.')}catch{setMessage('Stockage local indisponible. Enregistrez vos préférences avant de quitter.')}}
 return <main className="plan-share"><img src="/images/logo-yello-pro-v3.png" width="120" alt="Yello Pro"/><h1>Imaginez votre nouvel intérieur.</h1><p role="status">{message}</p>{recovery&&<div className="notice"><p>Des choix non transmis ont été retrouvés sur cet appareil.</p><button className="btn secondary" onClick={()=>{setPlan(recovery);setRecovery(null)}}>Reprendre mes choix</button><button className="btn ghost" onClick={()=>{localStorage.removeItem(key);setRecovery(null)}}>Conserver la version enregistrée</button></div>}{plan&&<><PlanEditor value={plan} onChange={change} client/><button className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/plans/view',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,version,plan})});const d=await r.json();if(!r.ok)throw Error(d.error);setPlan(d.plan);setVersion(d.version);try{localStorage.removeItem(key)}catch{}setRecovery(null);setMessage('Vos préférences sont enregistrées et accessibles à Yello Pro.');}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Enregistrer mes préférences</button></>}<p className="muted">Lien personnel valable 30 jours. Vos choix décoratifs ne modifient pas le devis ni les dimensions validées.</p></main>
}
