'use client';
import {useEffect,useState} from 'react';
import {features,plans,formatPrice} from '@/lib/plans';
export default function SubscriptionSettings(){
 const [state,setState]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[interval,setInterval]=useState('month');
 useEffect(()=>{fetch('/api/subscription').then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error);setState(data)}).catch(()=>setError('La démonstration ne dispose pas d’un abonnement réel. La facturation sera disponible après configuration de la base et de Stripe Yello Pro.'))},[]);
 async function pay(action:string,plan?:string){setBusy(true);setError('');try{const r=await fetch('/api/subscription',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,plan,interval})});const data=await r.json();if(!r.ok)throw Error(data.error);const url=new URL(data.url);if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname))throw Error('Lien de paiement invalide.');window.location.assign(url.href)}catch(e){setError(e instanceof Error?e.message:'Service indisponible.')}finally{setBusy(false)}}
 return <section className="panel"><header className="panel-header"><div><p className="eyebrow">VOTRE ENTREPRISE</p><h2>Abonnement Yello Pro</h2><p>La facturation de votre abonnement est séparée des factures de vos clients.</p></div></header><div style={{padding:'24px'}}>{error&&<p role="status" className="notice">{error}</p>}{state&&<p>Offre : <b>{plans.find(p=>p.code===state.subscription?.plan_code)?.name||'Aucune'}</b> · {state.subscription?.status==='trialing'?'Essai en cours':state.subscription?.status} · {state.usage.projects} projets actifs</p>}<div className="button-row"><button className="btn secondary" onClick={()=>setInterval(interval==='month'?'year':'month')}>{interval==='month'?'Mensuel · passer à l’annuel':'Annuel · passer au mensuel'}</button>{state?.subscription?.stripe_customer_id&&<button className="btn primary" disabled={busy||!state.owner||!state.configured} onClick={()=>pay('portal')}>Factures et gestion de l’abonnement</button>}</div><div className="yello-plan-grid">{plans.map(p=><article key={p.code} className="panel" style={{padding:'20px'}}><h3>{p.name}</h3><p><strong>{formatPrice(interval==='month'?p.monthly:p.annual)}</strong> / {interval==='month'?'mois':'an'}</p><p>{p.projects} projets · {p.admins} administrateur(s) · {p.workers} collaborateur(s)</p><ul>{p.features.map(f=><li key={f}>{features[f]}</li>)}</ul><button className="btn primary" disabled={busy||!state?.owner||!state?.configured} onClick={()=>pay('checkout',p.code)}>Choisir cette offre</button></article>)}</div></div></section>
}
