'use client';

import {useMemo,useState} from 'react';
import {ArrowUpRight,Columns3,Download,Search} from 'lucide-react';
import {money,type RecordItem} from '@/lib/model';
import {operationsFrom} from '@/lib/project-operations';
import {ledgerCost,supplierLedger,type LedgerFamily,type LedgerRow} from '@/lib/vendor-finance';
import {csvCell} from '@/lib/project-filters';

const tabs:['Tout'|LedgerFamily,string][]=[['Tout','Tout'],['Dépense','Dépenses'],['Facture fournisseur','Factures fournisseur'],['Crédit fournisseur','Crédits fournisseur'],['Paiement fournisseur','Paiements'],['Bon de commande','Bons de commande']];
const columns=[['reference','Réf.'],['project','Projet'],['family','Type'],['supplier','Fournisseur'],['description','Description'],['date','Date'],['dueOn','Échéance'],['costCode','Code de coût'],['subtotal','Avant taxes'],['tax','Taxes'],['total','Total'],['balance','Solde / non facturé'],['status','Statut']] as const;
type Column=typeof columns[number][0];
const defaultColumns:Column[]=['reference','project','family','supplier','date','total','status'];
const PAGE=20;

/** Company-wide view of every supplier-side document, filtered the same way for screen and export. */
export default function SupplierLedger({projects,expenses,clients,onOpenProject,onOpenRecord}:{projects:RecordItem[];expenses:RecordItem[];clients:RecordItem[];onOpenProject:(id:string,tab:string)=>void;onOpenRecord:(id:string)=>void}){
 const all=useMemo(()=>supplierLedger(projects,expenses,operationsFrom),[projects,expenses]);
 const [tab,setTab]=useState<'Tout'|LedgerFamily>('Tout'),[query,setQuery]=useState(''),[projectId,setProjectId]=useState(''),[supplier,setSupplier]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1);
 const [visible,setVisible]=useState<Column[]>(()=>{try{const saved=JSON.parse(localStorage.getItem('yello-pro-ledger-columns')||'null');return Array.isArray(saved)&&saved.length?saved:defaultColumns}catch{return defaultColumns}});
 const [drawer,setDrawer]=useState<Column[]|null>(null);
 const projectName=(id:string|null)=>{const p=projects.find(x=>x.id===id);if(!p)return id?'Information introuvable':'Sans projet';const c=clients.find(x=>x.id===p.client_id);return `${p.data.title||'Projet'}${c?` · ${c.data.name}`:''}`};
 const suppliers=[...new Set(all.map(r=>r.supplier).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'));
 const statuses=[...new Set(all.filter(r=>tab==='Tout'||r.family===tab).map(r=>r.status).filter(Boolean))].sort();
 const rows=all.filter(r=>(tab==='Tout'?r.family!=='Paiement fournisseur'&&r.family!=='Bon de commande':r.family===tab)&&(!projectId||r.projectId===projectId)&&(!supplier||r.supplier===supplier)&&(!status||r.status===status)&&(!from||r.date>=from)&&(!to||r.date<=to)&&`${r.reference} ${r.supplier} ${r.description} ${projectName(r.projectId)}`.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')));
 const cost=ledgerCost(rows);
 const pages=Math.max(1,Math.ceil(rows.length/PAGE)),current=Math.min(page,pages),shown=rows.slice((current-1)*PAGE,current*PAGE);
 const cell=(r:LedgerRow,c:Column)=>c==='project'?projectName(r.projectId):c==='family'?r.family:['subtotal','tax','total','balance'].includes(c)?money(r[c as 'total']):String(r[c as 'reference']||'—');
 function exportCsv(){const head=columns.filter(([k])=>visible.includes(k));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['﻿'+[head.map(([,l])=>l),...rows.map(r=>head.map(([k])=>['subtotal','tax','total','balance'].includes(k)?String(r[k as 'total']):cell(r,k)))].map(l=>l.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download=`yello-pro-fournisseurs-${tab}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const reset=()=>{setQuery('');setProjectId('');setSupplier('');setStatus('');setFrom('');setTo('');setPage(1)};
 const open=(r:LedgerRow)=>r.family==='Dépense'?onOpenRecord(r.sourceId):r.projectId&&onOpenProject(r.projectId,r.family==='Bon de commande'?'orders':'orders');
 return <section className="module-centre supplier-ledger">
  <div className="module-section-heading"><div><h2>Dépenses et fournisseurs</h2><p>Dépenses, factures, crédits, paiements et bons de commande de tous les projets. Les familles restent séparées : un paiement ou un bon n’est jamais additionné au coût.</p></div><div className="module-actions"><button className="btn secondary" onClick={()=>setDrawer([...visible])}><Columns3 size={15}/>Colonnes</button><button className="btn secondary" onClick={exportCsv}><Download size={15}/>Exporter</button></div></div>
  <div className="vendor-tabs" role="tablist" aria-label="Familles">{tabs.map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>{setTab(id);setStatus('');setPage(1)}}>{label}<span>{all.filter(r=>id==='Tout'?r.family!=='Paiement fournisseur'&&r.family!=='Bon de commande':r.family===id).length}</span></button>)}</div>
  <div className="module-filters"><label className="module-search"><Search size={16}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Fournisseur, réf., projet…" aria-label="Rechercher"/></label><label>Projet<select value={projectId} onChange={e=>{setProjectId(e.target.value);setPage(1)}}><option value="">Tous</option>{projects.map(p=><option key={p.id} value={p.id}>{String(p.data.title||'Projet')}</option>)}</select></label><label>Fournisseur<select value={supplier} onChange={e=>{setSupplier(e.target.value);setPage(1)}}><option value="">Tous</option>{suppliers.map(s=><option key={s}>{s}</option>)}</select></label><label>Statut<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Tous</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Du<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label>Au<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label><button className="btn ghost" onClick={reset}>Réinitialiser</button></div>
  <div className="portal-kpis">{tab==='Paiement fournisseur'?<div><dt>Payé</dt><dd>{money(rows.filter(r=>r.status.startsWith('Émis')).reduce((s,r)=>s+r.total,0))}</dd></div>:tab==='Bon de commande'?<><div><dt>Valeur engagée (envoyés)</dt><dd>{money(rows.filter(r=>['Envoyé','Partiellement reçu','Reçu'].includes(r.status)).reduce((s,r)=>s+r.subtotal,0))}</dd></div><div><dt>Non facturé</dt><dd>{money(rows.filter(r=>['Envoyé','Partiellement reçu','Reçu'].includes(r.status)).reduce((s,r)=>s+r.balance,0))}</dd></div></>:<><div><dt>Coût avant taxes</dt><dd>{money(cost.subtotal)}</dd></div><div><dt>Taxes</dt><dd>{money(cost.tax)}</dd></div><div><dt>Total taxes incluses</dt><dd>{money(cost.total)}</dd></div><div><dt>À payer</dt><dd>{money(cost.payable)}</dd></div></>}</div>
  {drawer&&<div className="filter-drawer" role="dialog" aria-label="Colonnes affichées" onKeyDown={e=>{if(e.key==='Escape')setDrawer(null)}}><h3>Colonnes affichées</h3><div className="settings-days">{columns.map(([k,label])=><label className="note-visibility" key={k}><input type="checkbox" checked={drawer.includes(k)} onChange={e=>setDrawer(e.target.checked?[...drawer,k]:drawer.filter(x=>x!==k))}/>{label}</label>)}</div><p className="muted">Ce choix est une préférence d’affichage sur cet appareil ; il ne modifie aucune écriture.</p><div className="module-actions"><button className="btn ghost" onClick={()=>setDrawer(defaultColumns)}>Réinitialiser</button><button className="btn secondary" onClick={()=>setDrawer(null)}>Annuler</button><button className="btn primary" disabled={!drawer.length} onClick={()=>{setVisible(drawer);try{localStorage.setItem('yello-pro-ledger-columns',JSON.stringify(drawer))}catch{};setDrawer(null)}}>Enregistrer</button></div></div>}
  {shown.length?<div className="vendor-table" role="region" aria-label="Écritures fournisseurs" tabIndex={0}><table><thead><tr>{columns.filter(([k])=>visible.includes(k)).map(([k,l])=><th key={k}>{l}</th>)}<th><span className="sr-only">Ouvrir</span></th></tr></thead><tbody>{shown.map(r=><tr key={r.id}>{columns.filter(([k])=>visible.includes(k)).map(([k])=><td key={k}>{cell(r,k)}</td>)}<td><button className="icon-button" aria-label={`Ouvrir ${r.reference||r.description||r.family}`} onClick={()=>open(r)}><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div>:<div className="portal-empty"><p>Aucun résultat pour ces filtres.</p></div>}
  <nav className="projects-pagination" aria-label="Pages"><button type="button" disabled={current===1} onClick={()=>setPage(current-1)}>Précédent</button><span>{rows.length?`${(current-1)*PAGE+1} à ${Math.min(rows.length,current*PAGE)} sur ${rows.length}`:'0 résultat'}</span><button type="button" disabled={current===pages} onClick={()=>setPage(current+1)}>Suivant</button></nav>
  <p className="muted">Les factures, crédits et paiements fournisseur se saisissent dans l’onglet Achats du projet concerné ; les dépenses dans Comptabilité. Créer, envoyer ou payer reste une action explicite : rien n’est transmis au fournisseur.</p>
 </section>;
}
