'use client';
import {useState} from 'react';
import type {Data,RecordItem} from '@/lib/model';
const states=['À faire','En cours','À valider','Validée'];
export function TaskDetails({data,onChange,tasks,id}:{data:Data;onChange:(data:Data)=>void;tasks:RecordItem[];id?:string}){
 const [text,setText]=useState('');const checklist:Array<{id:string;text:string;done:boolean}>=data.checklist||[];
 return <section className="task-details"><h3>Étapes et dépendances</h3><p className="muted">Découpez la tâche en étapes et indiquez ce qui doit être terminé avant de commencer.</p><label>Étiquettes (séparées par une virgule)<input value={(data.labels||[]).join(', ')} onChange={e=>onChange({...data,labels:e.target.value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,12)})}/></label><fieldset><legend>Liste de contrôle · {checklist.filter(x=>x.done).length}/{checklist.length}</legend>{checklist.map(item=><div className="checklist-row" key={item.id}><label><input type="checkbox" checked={item.done} onChange={e=>onChange({...data,checklist:checklist.map(x=>x.id===item.id?{...x,done:e.target.checked}:x)})}/>{item.text}</label><button type="button" className="btn ghost" aria-label={'Supprimer '+item.text} onClick={()=>onChange({...data,checklist:checklist.filter(x=>x.id!==item.id)})}>×</button></div>)}<div className="button-row"><input aria-label="Nouvelle étape" placeholder="Ajouter une étape…" value={text} maxLength={250} onChange={e=>setText(e.target.value)}/><button type="button" className="btn secondary" disabled={!text.trim()||checklist.length>=100} onClick={()=>{onChange({...data,checklist:[...checklist,{id:crypto.randomUUID(),text:text.trim(),done:false}]});setText('')}}>Ajouter</button></div></fieldset><label>Bloquée par<select value="" onChange={e=>{if(e.target.value)onChange({...data,dependencies:[...new Set([...(data.dependencies||[]),e.target.value])]})}}><option value="">Choisir une tâche du même projet…</option>{tasks.filter(x=>x.id!==id&&!(data.dependencies||[]).includes(x.id)).map(x=><option key={x.id} value={x.id}>{x.data.title}</option>)}</select></label>{(data.dependencies||[]).map((key:string)=><div className="checklist-row" key={key}><span>{tasks.find(x=>x.id===key)?.data.title||'Tâche indisponible'}</span><button type="button" className="btn ghost" onClick={()=>onChange({...data,dependencies:data.dependencies.filter((x:string)=>x!==key)})}>Retirer</button></div>)}</section>
}
export default function TaskWorkbench({tasks,projectName,onOpen,onMove,editable}:{tasks:RecordItem[];projectName:(id:string|null)=>string;onOpen:(id:string)=>void;onMove:(task:RecordItem,status:string)=>Promise<void>;editable:boolean}){
 const [view,setView]=useState('board'),[query,setQuery]=useState(''),[assignee,setAssignee]=useState(''),[sort,setSort]=useState('due'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rows=tasks.filter(t=>(!assignee||t.data.assignee===assignee)&&`${t.data.title} ${projectName(t.project_id)} ${(t.data.labels||[]).join(' ')}`.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))).sort((a,b)=>sort==='title'?String(a.data.title).localeCompare(String(b.data.title),'fr'):String(a.data.due||'9999').localeCompare(String(b.data.due||'9999')));
 async function move(task:RecordItem,status:string){setBusy(true);setError('');try{await onMove(task,status)}catch(e){setError(e instanceof Error?e.message:'Modification impossible.')}finally{setBusy(false)}}
 function card(t:RecordItem){const checks=t.data.checklist||[];return <article className="task-card" key={t.id} draggable={editable&&!busy} onDragStart={e=>e.dataTransfer.setData('text/plain',t.id)}><button className="task-open" onClick={()=>onOpen(t.id)}><p className="task-project">{projectName(t.project_id)}</p><h3>{t.data.title}</h3><div className="task-labels">{(t.data.labels||[]).map((label:string)=><span key={label}>{label}</span>)}</div><p>{t.data.due||'Sans échéance'} · {t.data.assignee||'Non affectée'}</p>{checks.length>0&&<small>{checks.filter((x:any)=>x.done).length}/{checks.length} étapes</small>}</button>{editable&&<select aria-label={'Statut de '+t.data.title} value={t.data.status||'À faire'} disabled={busy} onChange={e=>void move(t,e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select>}</article>}
 return <><div className="task-controls"><div className="button-row" role="group" aria-label="Vue des tâches">{[['board','Tableau'],['list','Liste'],['calendar','Échéances']].map(([id,label])=><button key={id} className={'btn '+(view===id?'primary':'secondary')} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div><div className="form-grid three"><label>Rechercher<input value={query} placeholder="Tâche, projet ou étiquette…" onChange={e=>setQuery(e.target.value)}/></label><label>Responsable<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Tout le monde</option>{[...new Set(tasks.map(t=>String(t.data.assignee||'')).filter(Boolean))].map(name=><option key={name}>{name}</option>)}</select></label><label>Trier<select value={sort} onChange={e=>setSort(e.target.value)}><option value="due">Échéance</option><option value="title">Nom</option></select></label></div></div>{error&&<p role="alert" className="error">{error}</p>}{!rows.length&&<p className="notice">Aucune tâche pour cette sélection.</p>}{view==='board'?<div className="kanban">{states.map(status=><section key={status} onDragOver={e=>{if(editable)e.preventDefault()}} onDrop={e=>{e.preventDefault();const task=rows.find(t=>t.id===e.dataTransfer.getData('text/plain'));if(task&&editable&&!busy)void move(task,status)}}><h2>{status}<small>{rows.filter(t=>(t.data.status||'À faire')===status).length}</small></h2>{rows.filter(t=>(t.data.status||'À faire')===status).map(card)}</section>)}</div>:view==='list'?<div className="task-list">{rows.map(card)}</div>:<div className="task-list">{[...new Set(rows.map(t=>t.data.due||'Sans échéance'))].sort().map(date=><section key={date}><h3>{date}</h3>{rows.filter(t=>(t.data.due||'Sans échéance')===date).map(card)}</section>)}</div>}</>
}
