'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Camera,Check,FileText,Mic,PenLine,Play,Pause,ShieldCheck,Layers,CalendarDays,Wallet,Users} from 'lucide-react';

const steps=[
 {title:'Préparer la visite',body:'Retrouvez le client, le lieu et les points à relever dans une seule fiche.',icon:CalendarDays,items:['Contexte du projet','Points à vérifier','Documents de référence']},
 {title:'Observer et capturer',body:'Sur téléphone ou tablette : photos, notes vocales, mesures et croquis au doigt ou au stylet.',icon:Camera,items:['Photo du lieu','Note vocale','Croquis et mesures']},
 {title:'Structurer le devis',body:'Organisez les lignes par catégorie, distinguez matériaux et main-d’œuvre, puis préparez les conditions.',icon:FileText,items:['Matériaux et main-d’œuvre','Marge et taxes','Échéancier de paiement']},
 {title:'Faire avancer le projet',body:'Rassemblez les étapes, les décisions et les documents à partager avec le client concerné.',icon:Check,items:['Phases et tâches','Documents sélectionnés','Décisions du client']}
];
export default function YelloShowcase(){
 const root=useRef<HTMLDivElement>(null),[step,setStep]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{const elements=root.current?.querySelectorAll('[data-reveal]');if(!elements)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.12});elements.forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setStep(old=>{if(old===steps.length-1){setPlaying(false);return old}return old+1}),4500);return()=>clearInterval(timer)},[playing]);
 const current=steps[step],Icon=current.icon;
 return <div ref={root} className="yl-showcase">
  <section className="yl-device-story" data-reveal aria-labelledby="device-title"><div className="yl-story-copy"><span className="yl-eyebrow">Au bureau. Sur le terrain.</span><h2 id="device-title">Le même contexte.<br/><span>À la bonne taille.</span></h2><p>Une administration pour l’entreprise, une interface adaptée au téléphone pour les visites, et de l’espace sur tablette pour annoter et dessiner.</p><ul><li><Mic size={18}/> Notes vocales pendant le relevé</li><li><PenLine size={18}/> Croquis au doigt ou au stylet</li><li><Camera size={18}/> Photos et documents dans le dossier</li></ul><a className="yl-text-link" href="#parcours">Découvrir le parcours <ArrowRight size={16}/></a></div><figure className="yl-visit-visual" onContextMenu={event=>event.preventDefault()} onDragStart={event=>event.preventDefault()}><img src="/images/visit-project-structure.webp" width="1536" height="1024" loading="lazy" draggable={false} alt="Plan de masse sur tablette et application de visite sur téléphone"/><figcaption>Visites, croquis, photos et notes vocales dans le même dossier.</figcaption></figure></section>
  <section id="parcours" className="yl-guided glass" data-reveal><div><span className="yl-eyebrow">Visite guidée interactive</span><h2>Une visite devient<br/><span>un projet structuré.</span></h2><p>Suivez les quatre étapes, ou choisissez celle qui vous intéresse.</p><button className="yl-btn yellow" onClick={()=>{if(!playing&&step===3)setStep(0);setPlaying(!playing)}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Mettre en pause':'Lire le parcours'}</button><div className="yl-tour-tabs" aria-label="Étapes du parcours">{steps.map((s,i)=><button key={s.title} aria-pressed={i===step} onClick={()=>{setPlaying(false);setStep(i)}}><span>0{i+1}</span>{s.title}</button>)}</div></div><div className="yl-tour-scene" key={step}><span className="yl-feature-icon"><Icon size={28}/></span><small>ÉTAPE 0{step+1} / 04</small><h3>{current.title}</h3><p>{current.body}</p><div className="yl-tour-items">{current.items.map(item=><div key={item}><Check size={17}/>{item}</div>)}</div><div className="yl-tour-progress">{steps.map((s,i)=><i key={s.title} className={i<=step?'done':''}/>)}</div></div></section>
  <section className="yl-field-photo" data-reveal><figure><img src="https://images.pexels.com/photos/6474459/pexels-photo-6474459.jpeg?auto=compress&amp;dpr=1&amp;h=750&amp;w=1260" width="1260" height="840" loading="lazy" alt="Une professionnelle consulte une tablette pendant un relevé dans un intérieur en travaux"/><figcaption>Photo d’illustration · <a href="https://www.pexels.com/photo/woman-wearing-white-helmet-while-holding-a-tablet-inside-the-house-6474459/" target="_blank" rel="noreferrer">Tima Miroshnichenko / Pexels</a></figcaption></figure><div className="glass"><span className="yl-eyebrow">Pensé pour le travail réel</span><h2>Le terrain a besoin<br/><span>de simplicité.</span></h2><p>Une observation, une mesure, un document : gardez le contexte pendant la visite, puis retrouvez-le pour préparer la suite du projet.</p></div></section>
  <section id="metiers" className="yl-section yl-audiences" data-reveal><span className="yl-eyebrow">Pour les entreprises qui coordonnent</span><h2>Un socle commun.<br/><span>Des usages selon votre métier.</span></h2><p className="yl-section-intro">Pour les indépendants, les équipes et les entreprises de services qui travaillent avec des clients et des intervenants. Les outils de terrain répondent aussi aux besoins spécifiques du bâtiment.</p><div className="yl-feature-grid">{[[Layers,'Construction & rénovation','Relevés, croquis, matériaux, main-d’œuvre, phases de chantier et ordres de changement.'],[PenLine,'Architecture & aménagement','Centralisez les plans, les annotations, les documents et les décisions à valider.'],[Users,'Agences & consultants','Organisez les missions, les livrables et les échanges dans un dossier par client.'],[CalendarDays,'Services & interventions','Préparez les rendez-vous, consignez les observations et retrouvez leur contexte.'],[Wallet,'Gestion & comptabilité','Rassemblez les factures, les dépenses, les justificatifs et les exports par période.'],[ShieldCheck,'Équipes & prestataires','Attribuez les tâches et sélectionnez les documents visibles pour chaque intervenant.']].map(([I,t,b])=>{const ItemIcon=I as typeof Layers;return <article key={String(t)} className="glass"><ItemIcon size={25}/><h3>{String(t)}</h3><p>{String(b)}</p></article>})}</div></section>
  <section className="yl-section yl-depth" data-reveal><span className="yl-eyebrow">L’administration de votre entreprise</span><h2>Le détail fait<br/><span>toute la différence.</span></h2><div className="yl-depth-grid">{[['Dossiers & organisation',['Fiches clients et contacts','Projets, phases et tâches','Calendrier et feuilles de temps','Journal et documents']],['Documents & chiffrage',['Devis par catégories','Matériaux, main-d’œuvre et marge','Contrats et signature','Demandes de prix et commandes']],['Finances & suivi',['Factures et paiements','Dépenses et justificatifs','Vue annuelle, client et projet','Dossier comptable à exporter']],['Collaboration & accès',['Portail du client concerné','Partage choisi par document','Notes internes distinctes','Historique et notifications']]].map(([title,items])=><article className="glass" key={String(title)}><h3>{title}</h3><ul>{(items as string[]).map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul></article>)}</div><p className="yl-activation-note">L’ouverture des comptes est en préparation. Les courriels, paiements et fonctions IA nécessitent des services connectés ; leur disponibilité dépend de la configuration de votre entreprise.</p></section>
 </div>
}
