"use client";
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Check,Layers,CalendarDays,FileText,Users,Activity,Mic,ShieldCheck,Menu,X,Sun} from 'lucide-react';
import YelloShowcase from './yello-showcase';
import {plans,formatPrice,features} from '@/lib/plans';
export default function YelloHome(){const [annual,setAnnual]=useState(true),[menu,setMenu]=useState(false);return <div className="yello-site">
 <header className="yl-header glass"><Link className="yl-logo" href="/"><span><Sun size={21}/></span>yello<span className="yl-pro">pro</span></Link><nav className={menu?'open':''}><a href="#outils" onClick={()=>setMenu(false)}>La plateforme</a><a href="#parcours" onClick={()=>setMenu(false)}>Le parcours</a><a href="#metiers" onClick={()=>setMenu(false)}>Pour qui ?</a><a href="#tarifs" onClick={()=>setMenu(false)}>Tarifs</a></nav><div className="yl-header-actions"><Link href="/connexion">Connexion</Link><Link className="yl-btn yellow" href="/connexion">Mon espace <ArrowUpRight size={15}/></Link><button className="yl-menu" aria-label={menu?'Fermer le menu':'Ouvrir le menu'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main><section className="yl-hero"><div className="yl-hero-copy"><span className="yl-eyebrow"><i/>Du premier contact au dernier détail</span><h1>Moins de dispersion.<br/><span>Plus de vision.</span></h1><p>Vos projets, vos équipes et vos finances.<br/>Un espace clair pour avancer ensemble.</p><div className="yl-cta"><Link href="/connexion" className="yl-btn dark">Accéder à mon espace <ArrowRight size={17}/></Link><a href="#tarifs" className="yl-btn glass">Trouver mon offre</a></div><small>Accès privé · connexion requise</small></div>
 <div className="yl-preview glass yl-preview-empty yl-hero-art"><img src="/yello-icon.svg" width="56" height="56" alt=""/><h3>Votre entreprise.<br/>Une vision claire.</h3><p>Vos projets, vos documents et vos équipes.<br/>Une administration privée, à votre rythme.</p><Link className="yl-btn yellow" href="/connexion">Accès privé <ArrowRight size={16}/></Link></div></section><section className="yl-pill-row" aria-label="Principaux outils">{['Projets','Devis & contrats','Équipe','Finances','Portail client'].map(x=><span key={x}><Check size={14}/>{x}</span>)}</section>
 <section id="outils" className="yl-section"><span className="yl-eyebrow">Une plateforme, toute votre activité</span><h2>Chaque outil à sa place.<br/><span>Chaque détail sous contrôle.</span></h2><div className="yl-feature-grid">{[[Layers,'Projets','Phases, tâches et calendrier : chacun sait ce qu’il doit faire.'],[FileText,'Devis & finances','Chiffrez, contractualisez et suivez vos factures et vos dépenses.'],[Users,'Clients & équipe','Partagez les bons documents avec les bonnes personnes.'],[Mic,'Sur le terrain','Capturez les mesures, photos, croquis et notes vocales pendant vos visites.'],[Activity,'Pilotage','Repérez les retards, les décisions en attente et la santé de vos projets.'],[ShieldCheck,'Un espace par entreprise','Les accès sont organisés par entreprise, projet et rôle.']].map(([Icon,title,body])=>{const I=Icon as typeof Layers;return <article className="glass" key={String(title)}><span className="yl-feature-icon"><I size={22}/></span><h3>{String(title)}</h3><p>{String(body)}</p></article>})}</div></section>
 <YelloShowcase/>
 <section id="methode" className="yl-method glass"><div><span className="yl-eyebrow">Simple à prendre en main</span><h2>Un fil conducteur.<br/>Du début à la fin.</h2><p>Un client, un projet, un espace partagé. Retrouvez le contexte, les décisions et les documents sans naviguer entre dix outils.</p><Link href="/connexion" className="yl-btn dark">Accéder à mon espace <ArrowRight size={16}/></Link></div><ol>{[['01','Organisez','Centralisez les clients, les projets et les tâches.'],['02','Construisez','Préparez les devis, contrats, visites et échéanciers.'],['03','Pilotez','Suivez les décisions, les paiements et l’avancement.']].map(([n,t,b])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></li>)}</ol></section>
 <section id="tarifs" className="yl-section yl-pricing"><span className="yl-eyebrow">Un abonnement qui grandit avec vous</span><h2>Vos outils.<br/><span>À votre rythme.</span></h2><p>Chaque offre inclut les outils de la précédente. Prix par entreprise, en CAD, hors taxes.</p><div className="yl-switch" aria-label="Période de facturation"><button aria-pressed={!annual} onClick={()=>setAnnual(false)}>Mensuel</button><button aria-pressed={annual} onClick={()=>setAnnual(true)}>Annuel <span>Économisez</span></button></div><div className="yl-price-grid">{plans.map((p,i)=><article key={p.code} className={`glass ${i===1?'featured':''}`}><small>{i===1?'POUR LES ENTREPRISES':'VOTRE PROCHAINE ÉTAPE'}</small><h3>{p.name}</h3><p>{p.description}</p><div className="yl-price">{formatPrice(annual?p.annual/12:p.monthly)}<span>/ mois</span></div><small>{annual?`${formatPrice(p.annual)} facturés par an`:'Facturation mensuelle'}</small><Link className={`yl-btn ${i===1?'yellow':'glass'}`} href={`/inscription?plan=${p.code}&interval=${annual?'year':'month'}`}>Choisir {p.name}<ArrowRight size={15}/></Link><p className="yl-limits">{p.admins} admin{p.admins>1?'s':''} · {p.workers} collaborateurs<br/>{p.projects} projets actifs · {p.storageGB} Go</p><ul>{p.features.filter(f=>i===0||!(plans[i-1].features as readonly string[]).includes(f)).map(f=><li key={f}><Check size={14}/>{features[f]}</li>)}</ul>{i>0&&<small>+ tous les outils de {plans[i-1].name}</small>}</article>)}</div><p className="yl-pricing-note">Les connexions à des services externes nécessitent leur configuration. Les fonctions IA dépendent d’une clé et de quotas. Les inscriptions et la facturation ne sont pas encore ouvertes.</p></section>
 <section className="yl-last glass"><h2>Votre prochaine étape,<br/><span>en toute clarté.</span></h2><Link className="yl-btn yellow" href="/connexion">Accéder à mon espace <ArrowUpRight size={18}/></Link></section></main><footer className="yl-footer"><Link className="yl-logo" href="/">yello<span className="yl-pro">pro</span></Link><span>Un espace pour avancer.</span><div><Link href="/confidentialite">Confidentialité</Link><Link href="/connexion">Connexion</Link><a href="#tarifs">Tarifs</a></div><small>© {new Date().getFullYear()} Yello Pro</small></footer></div>}
