"use client";
import YelloBrand from './yello-brand';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Check,Layers,CalendarDays,FileText,Users,Activity,Mic,ShieldCheck,Menu,X,Search,Bell,ChartNoAxesCombined,MapPin,PenLine,Camera} from 'lucide-react';
import YelloShowcase from './yello-showcase';
import {plans,formatPrice,features} from '@/lib/plans';
export default function YelloHome(){const [annual,setAnnual]=useState(true),[menu,setMenu]=useState(false);return <div className="yello-site">
 <header className="yl-header glass"><Link className="yl-logo" href="/"><YelloBrand/></Link><nav className={menu?'open':''}><a href="#outils" onClick={()=>setMenu(false)}>La plateforme</a><a href="#parcours" onClick={()=>setMenu(false)}>Le parcours</a><a href="#metiers" onClick={()=>setMenu(false)}>Pour qui ?</a><a href="#tarifs" onClick={()=>setMenu(false)}>Tarifs</a></nav><div className="yl-header-actions"><Link href="/connexion">Connexion</Link><Link className="yl-btn yellow" href="/connexion">Mon espace <ArrowUpRight size={15}/></Link><button className="yl-menu" aria-label={menu?'Fermer le menu':'Ouvrir le menu'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main><section className="yl-hero"><div className="yl-hero-copy"><span className="yl-eyebrow"><i/>Du premier contact au dernier détail</span><h1>Moins de dispersion.<br/><span>Plus de vision.</span></h1><p>Vos projets, vos équipes et vos finances.<br/>Un espace clair pour avancer ensemble.</p><div className="yl-cta"><Link href="/connexion" className="yl-btn dark">Accéder à mon espace <ArrowRight size={17}/></Link><a href="#tarifs" className="yl-btn glass">Trouver mon offre</a></div><small>Accès privé · connexion requise</small></div>
 <div className="yl-preview glass yl-hero-art yl-dashboard-art" aria-label="Illustration d’un tableau de bord Yello Pro, sans données d’entreprise">
   <div className="yl-dash-top"><YelloBrand/><div className="yl-dash-search"><Search size={12}/> Rechercher dans votre espace</div><Bell size={14}/><span className="yl-dash-avatar">Y</span></div>
   <div className="yl-dash-layout"><aside><b>Tableau de bord</b><span className="active">Vue d’ensemble</span><span>Projets</span><span>Devis & contrats</span><span>Clients</span><span>Finances</span><span>Documents</span></aside><div className="yl-dash-body"><div className="yl-dash-greeting"><div><small>VOTRE ACTIVITÉ</small><h3>Une journée claire.</h3></div><span>Cette semaine</span></div><div className="yl-dash-stats"><div><small>Projets actifs</small><b>—</b><em>suivi en temps réel</em></div><div><small>Décisions</small><b>—</b><em>à organiser</em></div><div><small>Finances</small><b>—</b><em>vue consolidée</em></div></div><div className="yl-dash-panels"><div className="yl-dash-projects"><div><b>Avancement des projets</b><ArrowRight size={14}/></div>{['Préparer','Coordonner','Finaliser'].map((label,i)=><p key={label}><span>{label}</span><i><b style={{width:`${65-i*14}%`}}/></i><em>{65-i*14}%</em></p>)}</div><div className="yl-dash-chart"><ChartNoAxesCombined size={18}/><b>Votre vision</b><svg viewBox="0 0 220 70" aria-hidden="true"><path d="M0 53 31 42 58 48 85 27 112 34 144 15 177 23 220 4"/></svg><small>Un aperçu s’affiche dès vos premières actions.</small></div></div></div></div>
   <div className="yl-dash-float"><span className="yl-feature-icon"><PenLine size={18}/></span><div><b>Sur le terrain</b><small>Photos · croquis · notes vocales</small></div></div><small className="yl-art-caption">Illustration de l’interface · aucun dossier réel affiché</small>
 </div></section><section className="yl-pill-row" aria-label="Principaux outils">{['Projets','Devis & contrats','Équipe','Finances','Portail client'].map(x=><span key={x}><Check size={14}/>{x}</span>)}</section>
 <section id="outils" className="yl-section"><span className="yl-eyebrow">Une plateforme, toute votre activité</span><div className="yl-section-heading"><h2>Chaque outil à sa place.<br/><span>Chaque détail sous contrôle.</span></h2><p>Une même logique pour le bureau, le chantier et le client : le bon niveau de détail, au bon moment.</p></div><div className="yl-feature-grid yl-feature-grid-rich">{[[Layers,'Projets','Phases, tâches et calendrier : chacun sait ce qu’il doit faire.','project'],[FileText,'Devis & finances','Chiffrez, contractualisez et suivez vos factures et vos dépenses.','quote'],[Users,'Clients & équipe','Partagez les bons documents avec les bonnes personnes.','people'],[Mic,'Sur le terrain','Capturez les mesures, photos, croquis et notes vocales pendant vos visites.','field'],[Activity,'Pilotage','Repérez les retards, les décisions en attente et la santé de vos projets.','insights'],[ShieldCheck,'Un espace par entreprise','Les accès sont organisés par entreprise, projet et rôle.','access']].map(([Icon,title,body,kind])=>{const I=Icon as typeof Layers;return <article className="glass" key={String(title)}><span className="yl-feature-icon"><I size={22}/></span><h3>{String(title)}</h3><p>{String(body)}</p><div className={`yl-card-visual ${kind}`} aria-hidden="true">{kind==='project'&&<><i/><i/><i/></>}{kind==='quote'&&<><b>Devis</b><span/><span/><em/></>}{kind==='people'&&<><span>●</span><span>●</span><span>●</span><i>+ accès choisi</i></>}{kind==='field'&&<><Camera/><span>Photos</span><Mic/><span>Note vocale</span></>}{kind==='insights'&&<svg viewBox="0 0 180 55"><path d="M0 43 35 37 58 42 91 16 120 27 150 10 180 18"/></svg>}{kind==='access'&&<><b>Documents</b><span>Visible par le client</span><span>Interne seulement</span></>}</div></article>})}</div></section>
 <YelloShowcase/>
 <section id="methode" className="yl-method glass"><div><span className="yl-eyebrow">Simple à prendre en main</span><h2>Un fil conducteur.<br/>Du début à la fin.</h2><p>Un client, un projet, un espace partagé. Retrouvez le contexte, les décisions et les documents sans naviguer entre dix outils.</p><Link href="/connexion" className="yl-btn dark">Accéder à mon espace <ArrowRight size={16}/></Link></div><ol>{[['01','Organisez','Centralisez les clients, les projets et les tâches.'],['02','Construisez','Préparez les devis, contrats, visites et échéanciers.'],['03','Pilotez','Suivez les décisions, les paiements et l’avancement.']].map(([n,t,b])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></li>)}</ol></section>
 <section id="tarifs" className="yl-section yl-pricing"><span className="yl-eyebrow">Un abonnement qui grandit avec vous</span><h2>Vos outils.<br/><span>À votre rythme.</span></h2><p>Chaque offre inclut les outils de la précédente. Prix par entreprise, en CAD, hors taxes.</p><div className="yl-switch" aria-label="Période de facturation"><button aria-pressed={!annual} onClick={()=>setAnnual(false)}>Mensuel</button><button aria-pressed={annual} onClick={()=>setAnnual(true)}>Annuel <span>Économisez</span></button></div><div className="yl-price-grid">{plans.map((p,i)=><article key={p.code} className={`glass ${i===1?'featured':''}`}><small>{i===1?'POUR LES ENTREPRISES':'VOTRE PROCHAINE ÉTAPE'}</small><h3>{p.name}</h3><p>{p.description}</p><div className="yl-price">{formatPrice(annual?p.annual/12:p.monthly)}<span>/ mois</span></div><small>{annual?`${formatPrice(p.annual)} facturés par an`:'Facturation mensuelle'}</small><Link className={`yl-btn ${i===1?'yellow':'glass'}`} href={`/inscription?plan=${p.code}&interval=${annual?'year':'month'}`}>Choisir {p.name}<ArrowRight size={15}/></Link><p className="yl-limits">{p.admins} admin{p.admins>1?'s':''} · {p.workers} collaborateurs<br/>{p.projects} projets actifs · {p.storageGB} Go</p><ul>{p.features.filter(f=>i===0||!(plans[i-1].features as readonly string[]).includes(f)).map(f=><li key={f}><Check size={14}/>{features[f]}</li>)}</ul>{i>0&&<small>+ tous les outils de {plans[i-1].name}</small>}</article>)}</div><p className="yl-pricing-note">Les connexions à des services externes nécessitent leur configuration. Les fonctions IA dépendent d’une clé et de quotas. Les inscriptions et la facturation ne sont pas encore ouvertes.</p></section>
 <section className="yl-last glass"><h2>Votre prochaine étape,<br/><span>en toute clarté.</span></h2><Link className="yl-btn yellow" href="/connexion">Accéder à mon espace <ArrowUpRight size={18}/></Link></section></main><footer className="yl-footer"><Link className="yl-logo" href="/"><YelloBrand/></Link><span>Un espace pour avancer.</span><div><Link href="/confidentialite">Confidentialité</Link><Link href="/connexion">Connexion</Link><a href="#tarifs">Tarifs</a></div><small>© {new Date().getFullYear()} Yello Pro</small></footer></div>}
