import Decimal from 'decimal.js';
import {documentRule,lineAmounts,profitOn} from './pricing';
export type Role = 'admin'|'worker'|'client';
export type Kind = 'client'|'request'|'project'|'phase'|'contract'|'specification'|'task'|'visit'|'quote'|'partner_quote'|'invoice'|'expense'|'message'|'document'|'settings'|'journal';
export type Data = Record<string, any>;
export type RecordItem = {id:string;kind:Kind;client_id:string|null;project_id:string|null;data:Data;version:number;created_at:string;updated_at:string};
export type Profile = {id:string;name:string;email:string;role:Role;client_id:string|null};
export const kinds:Kind[]=['client','request','project','phase','contract','specification','task','visit','quote','partner_quote','invoice','expense','message','document','settings','journal'];
export const round=(n:number)=>new Decimal(n).toDecimalPlaces(2,Decimal.ROUND_HALF_UP).toNumber();
export const money=(n:number)=>new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2}).format(n||0);
export function totals(data:Data){const cent=(n:Decimal)=>n.toDecimalPlaces(2,Decimal.ROUND_HALF_UP);const amounts=(data.lines||[]).map((l:Data)=>lineAmounts(l));const baseSubtotal=amounts.reduce((s:Decimal,a:{base:number})=>s.plus(a.base),new Decimal(0));const lineMargin=amounts.reduce((s:Decimal,a:{profit:number})=>s.plus(a.profit),new Decimal(0));const subtotal=baseSubtotal.plus(lineMargin);const markup=profitOn(subtotal,documentRule(data));const beforeDiscount=subtotal.plus(markup);const discount=cent(beforeDiscount.times(data.discount||0).div(100));const net=beforeDiscount.minus(discount);const tps=cent(net.times(data.tps??5).div(100));const tvq=cent(net.times(data.tvq??9.975).div(100));const result={subtotal:subtotal.toNumber(),discount:discount.toNumber(),net:net.toNumber(),tps:tps.toNumber(),tvq:tvq.toNumber(),total:net.plus(tps).plus(tvq).toNumber()};return lineMargin.isZero()&&markup.isZero()?result:{...result,baseSubtotal:baseSubtotal.toNumber(),lineMargin:lineMargin.toNumber(),markup:markup.toNumber()};}
export const statuses:Record<string,string[]>={client:['Prospect','Actif','Ancien client'],request:['Nouvelle','À contacter','Visite planifiée','Devis envoyé','Gagnée','Perdue'],project:['Planifié','En cours','En pause','Terminé'],phase:['À planifier','En cours','En attente','Terminée'],contract:['Brouillon','Envoyé','Signé','Archivé'],specification:['Brouillon','Validé','Partagé','Archivé'],task:['À faire','En cours','À valider','Validée'],quote:['Brouillon','Validé','Envoyé','Accepté','Refusé'],partner_quote:['À chiffrer','Brouillon','Envoyé','Accepté','Refusé'],invoice:['Brouillon','Émise','Partiellement payée','Payée'],visit:['En cours','Validée']};
export const defaults={name:'Yello Pro',phone:'',email:'',address:'',rbq:'',tps:5,tvq:9.975,tps_number:'',tvq_number:'',accountant:'',calendly_url:'',appointment_duration:60,travel_buffer:60,seo_title:'Yello Pro | Rénovation à Laval et Montréal',seo_description:'Rénovations de cuisines, salles de bain, sous-sols et agrandissements à Laval, Montréal et sur la Rive-Nord. Demandez votre soumission.',terms:'Soumission valable 30 jours. Travaux supplémentaires soumis à une approbation écrite. Échéancier et modalités de paiement à convenir avant le début du chantier.',contract_terms:'',validity:'30 jours',payment_schedule:[{label:'Dépôt',percent:15},{label:'Début des travaux',percent:35},{label:'Milieu des travaux',percent:40},{label:'Fin des travaux',percent:10}]};
export type PaymentStep={label:string;percent:number};
export const defaultPaymentSchedule:PaymentStep[]=[{label:'Dépôt',percent:15},{label:'Début des travaux',percent:35},{label:'Milieu des travaux',percent:40},{label:'Fin des travaux',percent:10}];
// Split a total into the configured payment milestones (last step absorbs rounding).
export function paymentRows(total:number,schedule:PaymentStep[]=defaultPaymentSchedule){const valid=Array.isArray(schedule)&&schedule.length>0&&schedule.every(s=>Number.isFinite(Number(s.percent))&&Number(s.percent)>0)&&Math.abs(schedule.reduce((sum,s)=>sum+Number(s.percent),0)-100)<0.001;const steps=valid?schedule:defaultPaymentSchedule;let allocated=0;return steps.map((s,i)=>{const amount=i===steps.length-1?round(total-allocated):round(total*Number(s.percent)/100);allocated=round(allocated+amount);return {label:s.label,percent:Number(s.percent),amount};});}
export function permitted(role:Role,kind:Kind){return role==='admin'||(role==='worker'&&['project','phase','contract','specification','task','document','message','partner_quote'].includes(kind))||(role==='client'&&['client','project','phase','contract','specification','quote','invoice','message','document'].includes(kind));}
