import {safePaymentUrl} from './billing';
import {clientPricing} from './client-pricing';
import {documentNotes} from './document-notes';
import {Profile,RecordItem} from './model';
import {clientPlan} from './plan';
import {scheduleFrom} from './schedule';
import {clientRequestsFrom} from './client-requests';
/** Client/worker copy of a published schedule: dates, titles and progress only (no assignees). */
export const publishedSchedule=(value:unknown)=>scheduleFrom(value).map(({id,title,kind,start,days,progress,predecessor,color})=>({id,title,kind,start,days,progress,predecessor,color,assignee:''}));
export function redact(user:Profile,r:RecordItem):RecordItem{if(user.role==='admin')return r;r={...r,data:documentNotes(r.data,user.role)};if(user.role==='client'&&['quote','invoice','contract'].includes(r.kind))r={...r,data:clientPricing(r.data)};if(r.kind==='project'){const {title,status,start,end,address,service,plan}=r.data;let visiblePlan;try{visiblePlan=plan?clientPlan(plan):undefined}catch{visiblePlan=undefined}return {...r,data:{title,status,start,end,address,service,plan:visiblePlan,selections:(r.data.selections||[]).filter((x:any)=>x.published===true).map((x:any)=>({id:x.id,title:x.title,notes:x.notes,date:x.date,published:true,options:(x.options||[]).map((o:any)=>({id:o.id,name:o.name,url:o.url,price:o.price})),decision:x.decision?{optionId:x.decision.optionId,at:x.decision.at}:undefined})),construction_reports:(r.data.construction_reports||[]).filter((x:any)=>x.published===true).map((x:any)=>({id:x.id,title:x.title,notes:x.notes,date:x.date,progress:x.progress,scope:x.scope})),client_requests:user.role==='client'?clientRequestsFrom(r.data.client_requests):[],schedule:r.data.schedule_published===true?publishedSchedule(r.data.schedule):[],schedule_published:r.data.schedule_published===true,operations:{dailyLogs:Array.isArray(r.data.operations?.dailyLogs)?r.data.operations.dailyLogs.filter((log:any)=>log.sharedWithClient===true).map((log:any)=>({id:log.id,date:log.date,summary:log.summary,blockers:log.blockers,sharedWithClient:true})):[]}}};}if(r.kind==='client'){const {name,email,phone,address}=r.data;const groups=user.role==='worker'?(r.data.message_groups||[]).filter((group:any)=>group.participants?.includes(user.id)):undefined;return {...r,data:{name,email,phone,address,...(groups?{message_groups:groups}:{})}};}if(r.kind==='contract'){const {notes,totals,costs,internal_costs,profit,...data}=r.data;return {...r,data};}if(r.kind==='quote'||r.kind==='invoice'){const {number,title,status,date,due,lines,tps,tvq,discount,markup,terms,paid,public_token,payment_url,first_viewed_at,rooms,material_selection,payment_schedule,validity,notes,client_view}=r.data;return {...r,data:{number,title,status,date,due,lines,tps,tvq,discount,markup,terms,paid,...(user.role==='client'?{public_token,payment_url:safePaymentUrl(payment_url),first_viewed_at}:{}),rooms:Array.isArray(rooms)?rooms.map(({name,length,width,height,unit,materials}:any)=>({name,length,width,height,unit,materials})):[],material_selection,payment_schedule,validity,client_view,...(user.role==='worker'?{notes}:{})}};}return r;}
