export type ScheduleActivity={id:string;title:string;kind:'group'|'activity'|'milestone';start:string;days:number;progress:number;assignee:string;predecessor:string;color:string;parent?:string};
function validDate(value:unknown):value is string {if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(value+'T12:00:00Z');return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===value}
export function scheduleFrom(value:unknown):ScheduleActivity[]{return Array.isArray(value)?value.filter(x=>x&&typeof x==='object').map(x=>({id:String(x.id),title:String(x.title||''),kind:['group','activity','milestone'].includes(x.kind)?x.kind:'activity',start:validDate(x.start)?x.start:'',days:x.kind==='milestone'?0:Math.min(1000,Math.max(1,Math.floor(Number(x.days)||1))),progress:Math.min(100,Math.max(0,Number(x.progress)||0)),assignee:String(x.assignee||''),predecessor:String(x.predecessor||''),color:/^#[0-9a-f]{6}$/i.test(x.color)?x.color:'#6f927b',...(typeof x.parent==='string'&&x.parent?{parent:x.parent}:{})})):[]}
export function addDay(value:string,days:number){const date=new Date(value+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
/** workdays: true = Monday–Friday, false = every day, or ISO weekdays (1 = Monday … 7 = Sunday) from the settings. */
export type WorkWeek=boolean|number[];
export function workingDay(value:string,workdays:WorkWeek,holidays:string[]=[]){const day=new Date(value+'T12:00:00Z').getUTCDay();const iso=day||7;const open=Array.isArray(workdays)?(workdays.length?workdays.includes(iso):true):(!workdays||![0,6].includes(day));return open&&!holidays.includes(value)}
export function scheduleEnd(activity:ScheduleActivity,workdays:WorkWeek=true,holidays:string[]=[]){if(!activity.start)return '';let date=activity.start,remaining=Math.max(1,activity.days);for(let i=0;i<10000;i++){if(workingDay(date,workdays,holidays))remaining--;if(remaining<=0)return date;date=addDay(date,1)}throw new Error('Durée d’activité trop longue.')}
export function scheduleError(activities:ScheduleActivity[]){const ids=new Set(activities.map(x=>x.id));if(ids.size!==activities.length)return 'Deux activités ont le même identifiant.';if(activities.some(x=>!x.title.trim()))return 'Donnez un titre à chaque activité.';if(activities.some(x=>x.predecessor&&!ids.has(x.predecessor)))return 'Une activité précédente a été retirée. Corrigez la dépendance.';if(activities.some(x=>x.parent&&!activities.some(g=>g.id===x.parent&&g.kind==='group')))return 'Une activité est rangée dans un groupe absent. Choisissez un autre groupe.';if(activities.some(x=>{const seen=new Set<string>();let cur=x.parent;while(cur){if(cur===x.id||seen.has(cur))return true;seen.add(cur);cur=activities.find(g=>g.id===cur)?.parent}return false}))return 'Un groupe ne peut pas se contenir lui-même.';const visited=new Set<string>(),path=new Set<string>();function cycle(id:string):boolean{if(path.has(id))return true;if(visited.has(id))return false;path.add(id);const previous=activities.find(x=>x.id===id)?.predecessor;if(previous&&cycle(previous))return true;path.delete(id);visited.add(id);return false}return activities.some(x=>cycle(x.id))?'Les dépendances forment un cycle. Retirez le lien qui revient à une activité précédente.':''}
export function recalculateSchedule(activities:ScheduleActivity[],workdays:WorkWeek=true,holidays:string[]=[]){const error=scheduleError(activities);if(error)throw new Error(error);const result=structuredClone(activities),done=new Set<string>();function visit(item:ScheduleActivity){if(done.has(item.id))return;if(item.predecessor){const previous=result.find(x=>x.id===item.predecessor)!;visit(previous);const end=scheduleEnd(previous,workdays,holidays);if(end){let start=addDay(end,1);for(let i=0;!workingDay(start,workdays,holidays)&&i<10000;i++)start=addDay(start,1);item.start=start}}done.add(item.id)}result.forEach(visit);return result}

/** Depth of an activity in nested groups (0 = top level). */
export function depth(activities:ScheduleActivity[],id:string){let d=0,cur=activities.find(x=>x.id===id)?.parent;const seen=new Set<string>();while(cur&&!seen.has(cur)&&d<20){seen.add(cur);d++;cur=activities.find(x=>x.id===cur)?.parent}return d}
/** Every activity nested (directly or not) under a group. */
export function descendants(activities:ScheduleActivity[],groupId:string):ScheduleActivity[]{const direct=activities.filter(x=>x.parent===groupId);return [...direct,...direct.filter(x=>x.kind==='group').flatMap(x=>descendants(activities,x.id))]}
/** Span of a group computed from its dated descendants. */
export function groupSpan(activities:ScheduleActivity[],groupId:string,workdays:WorkWeek=true,holidays:string[]=[]){const dated=descendants(activities,groupId).filter(x=>x.start&&x.kind!=='group');if(!dated.length)return null;return {start:dated.map(x=>x.start).sort()[0],end:dated.map(x=>scheduleEnd(x,workdays,holidays)).sort().at(-1)!}}
/** Move (keeping duration) or resize by whole days; a milestone keeps zero duration. Pure: returns a new activity. */
export function shiftActivity(activity:ScheduleActivity,deltaDays:number):ScheduleActivity{if(!activity.start||!deltaDays)return activity;return {...activity,start:addDay(activity.start,deltaDays)}}
export function resizeActivity(activity:ScheduleActivity,deltaDays:number):ScheduleActivity{if(activity.kind==='milestone')return activity;return {...activity,days:Math.min(1000,Math.max(1,activity.days+deltaDays))}}
