import {accountingReport} from '@/lib/accounting';
import {NextResponse} from 'next/server';
import {identity,db} from '@/lib/supabase';
import {sameOrigin} from '@/lib/access';
import {makePdf} from '@/lib/pdf';
import {defaults,money,Data} from '@/lib/model';
import {ccSchema,recipients} from '@/lib/email';
import {z} from 'zod';
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({error:'Origine refusée.'},{status:403});const user=await identity();if(user?.role!=='admin')return NextResponse.json({error:'Accès refusé.'},{status:403});if(!process.env.RESEND_API_KEY||!process.env.MAIL_FROM)return NextResponse.json({error:'Le service de courriel doit être activé.'},{status:503});const p=z.object({email:z.email(),cc:ccSchema,from:z.union([z.iso.date(),z.literal('')]).optional(),to:z.iso.date().optional()}).safeParse(await req.json());if(!p.success)return NextResponse.json({error:'Courriel ou copie invalide.'},{status:400});const {data:rows,error}=await (await db()).from('records').select('*').eq('kind','journal').order('created_at');if(error)return NextResponse.json({error:'Lecture du journal impossible.'},{status:503});const settings=(await (await db()).from('records').select('data').eq('kind','settings').limit(1).maybeSingle()).data?.data||defaults;const lines=accountingReport(rows||[],p.data.from||'',p.data.to||new Date().toISOString().slice(0,10)).reportLines;const bytes=await makePdf('Rapport comptable',{reportLines:lines},{},settings);const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.MAIL_FROM,...recipients(p.data.email,p.data.cc),subject:'Yello Pro — Rapport comptable',text:'Bonjour,\n\nVeuillez trouver le rapport comptable en pièce jointe.\n\nYello Pro',attachments:[{filename:'rapport-mgpro.pdf',content:Buffer.from(bytes).toString('base64')}]})});if(!res.ok)return NextResponse.json({error:'Le prestataire n’a pas confirmé l’envoi.'},{status:502});await (await db()).from('audit_log').insert({actor_id:user.id,action:'accounting_report_sent',details:{recipient:p.data.email,cc:p.data.cc}});return NextResponse.json({ok:true});}
