'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createBrowserClient} from '@supabase/ssr';
import YelloBrand from '@/components/yello-brand';
export default function Account(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const auth=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);let live=true;auth.auth.getSession().then(({data})=>{if(live)setReady(Boolean(data.session));});const {data}=auth.auth.onAuthStateChange((_event,session)=>{if(live)setReady(Boolean(session));});return()=>{live=false;data.subscription.unsubscribe();};},[]);
 return <div className="login-page"><div className="login-intro"><Link href="/" className="yello-logo"><YelloBrand/></Link><div><p className="eyebrow">VOTRE ESPACE PRIVÉ</p><h1>Bienvenue dans<br/>Yello Pro.</h1><p>Choisissez votre mot de passe personnel pour accéder à votre entreprise.</p></div></div><div className="login-form"><h2>Définir mon mot de passe</h2><p>Utilisez au moins 12 caractères.</p>{!ready&&<p className="notice">Ouvrez le dernier lien reçu par courriel pour activer ce formulaire.</p>}<form onSubmit={async e=>{e.preventDefault();setMessage('');const form=new FormData(e.currentTarget),password=String(form.get('password'));if(password!==form.get('confirmation')){setMessage('Les mots de passe ne correspondent pas.');return;}setBusy(true);try{const auth=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {error}=await auth.auth.updateUser({password});if(error)setMessage('Le lien a expiré ou le mot de passe est invalide. Demandez une nouvelle invitation.');else location.href='/admin';}catch{setMessage('Connexion indisponible. Réessayez.');}finally{setBusy(false);}}}><label>Nouveau mot de passe<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label>Confirmer le mot de passe<input name="confirmation" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><button className="btn primary full" disabled={!ready||busy}>{busy?'Enregistrement…':'Activer mon accès'}</button><p role="status">{message}</p></form><Link href="/connexion">Retour à la connexion</Link></div></div>;
}
