from pathlib import Path
import json
original=json.loads(Path('content/original.json').read_text(encoding='utf-8'))
translations={
'a-propos':('General contractor',[
('Complete management for your renovation project',"Rénovations MG Pro is your general contractor in Laval and on the North Shore. With more than 20 years of experience in renovation and construction, our team handles projects ranging from bathroom renovations to basement finishing. We work with trusted subcontractors and coordinate the trades for turnkey residential and commercial renovations. We offer a free estimate so you can plan your budget before committing to the work.","Respect for your home, budget and schedule matters to us. We keep the worksite clean and safe, clean up before handing it back, and establish realistic timelines. We serve homeowners and businesses in Laval and the Laurentians, including kitchens, bathrooms, offices, hair salons and other commercial spaces. Our team uses durable materials and careful workmanship.","Planning a full home renovation? We also manage major construction and renovation projects in Fabreville, Chomedey, Sainte-Rose, Laval-sur-le-Lac, Laval-Ouest, Sainte-Dorothée, Auteuil and Vimont."),
('Outdoor renovation',"We also handle exterior renovation in Laval, on the North Shore and throughout the Laurentians. Our services include building and renovating balconies and decks.","We can design landscaping to suit your property and install fences for greater privacy. Let our team manage your deck project so you can enjoy your backyard."),
('Our service area',"We serve Laval, Montréal and the North Shore for residential and commercial construction and renovation. Contact us for a free estimate and a complete approach to your project.")]),
'cuisine-haut-de-gamme':('Luxury kitchens',[
('A kitchen designed around you',"Dreaming of a luxurious kitchen? MG Pro serves Laval, Montréal and the North Shore with a turnkey service that covers your project from start to finish. We also work with architects and architectural technologists to prepare custom plans.","We take the time to understand your ideas, preferences and everyday needs. Ask for a free estimate for a kitchen that reflects your style."),
('The details that make your kitchen work',"Careful planning starts with your habits, your tastes and the space available. A waterfall countertop can add a distinctive edge to an island, while an integrated range hood changes the overall look. A walk-in pantry improves storage and access; a wine cellar or wine storage area adds a decorative feature.","Cabinet and drawer organizers make a difference every day, even when they are out of sight. Consider the hardware, countertop and cabinet materials, and the performance of your appliances alongside the overall design."),
('Countertop materials',"Countertops strongly influence the finished appearance of a kitchen. Compare the look, maintenance and limitations of each material before choosing."),
('Marble',"An elegant, timeless natural stone. Sealing and appropriate care help preserve its appearance. Confirm the maintenance requirements of the particular product you choose."),
('Granite',"Each slab has its own pattern. Granite is valued for durability and heat resistance. Follow the supplier’s sealing and care instructions for the selected stone."),
('Vetrazzo',"Made with recycled glass, Vetrazzo adds distinctive colour and texture. Ask the supplier about the sealing and maintenance requirements of your selected finish."),
('Quartz',"Quartz offers a stone-like look and is easy to maintain. It is resistant to everyday staining and scratching, but hot cookware can damage or discolour it: use suitable protection."),
('Bring your dream kitchen to life',"Our team offers custom plans and a turnkey renovation service throughout Laval, Montréal and the North Shore. Explore financing through Financeit; eligibility and current promotional terms must be confirmed with the provider.")]),
'salle-de-bain':('Bathrooms',[
('A bathroom suited to your needs',"Is your bathroom outdated or no longer practical? Would you like to add one to your home or business? MG Pro helps homeowners and businesses in Laval and on the North Shore reconfigure bathrooms, including freestanding tubs, tiled showers and steam bathing features.","Before work starts, we provide a free estimate and a planned schedule. We coordinate plumbing changes and install flooring, ceramic tile, vanities, showers and baths.","With more than 20 years of renovation experience, we serve Chomedey, Vimont, Sainte-Rose, Sainte-Dorothée, Auteuil, Laval-Ouest, Fabreville, Duvernay and Laval-sur-le-Lac."),
('Tiled showers',"We can design a walk-in tiled shower, a tiled shower with an acrylic base, or a bath-and-shower combination. Glass doors and a continuous floor can help create a feeling of space.","Installation includes the appropriate slope for drainage and the selected wall and floor finishes. We pay attention to usability, cleaning and the details of the finished shower."),
('Planning your bathroom renovation',"Function, appearance, comfort and maintenance are important considerations. An attractive bathroom that does not need major work may also appeal to future buyers; the outcome depends on your property and market.","Consider water-resistant, easy-care flooring, timeless wall colours and long-lasting finishes. If your bath or shower is worn, a replacement can transform the room. Discuss your priorities with our team and request a free estimate."),
('Service area',"We renovate bathrooms in Laval, Montréal and the North Shore, including Pointe-Claire, Blainville, Rosemère, Lorraine, Bois-des-Filion, Boisbriand, Sainte-Thérèse, Saint-Eustache, Saint-Colomban and Saint-Jérôme."),
('Ready for a new bathroom?',"Whether you are creating a bathroom or updating an existing one, share your plans with MG Pro. We will help you assess the work and prepare a free estimate.")]),
'sous-sol':('Basements',[
('Make the most of your basement',"MG Pro provides turnkey basement finishing in Laval, on the North Shore and throughout the Laurentians, from the free estimate to the final inspection. Turn an underused area into comfortable living space and useful storage.","A basement can become a children’s playroom, home theatre, family lounge, bedroom, office or additional bathroom. We coordinate plumbing, drywall, joint finishing, painting and flooring, with close attention to the finishing details.","A well-planned basement can improve your home’s usefulness and appeal. We serve Laval, Fabreville, Duvernay, Chomedey, Sainte-Rose, Vimont, Sainte-Dorothée, Laval-sur-le-Lac, Auteuil, Laval-Ouest and Greater Montréal."),
('A bar in your basement',"Create a welcoming place to relax with family and friends, tailored to your taste and budget. We can include a sink, refrigerator and other practical features, coordinating the plumbing and electrical work needed for a functional space.","We plan the work and schedule with you so you know when to expect your new space."),
('Our service area',"Our basement renovation and finishing services cover Laval, Montréal and the North Shore, including Pointe-Claire, Blainville, Rosemère, Lorraine, Bois-des-Filion, Boisbriand, Sainte-Thérèse, Saint-Eustache, Saint-Colomban and Saint-Jérôme."),
('Plan your basement renovation',"From drywall to flooring and the final finish, our team coordinates every stage. Contact us to discuss your project and obtain a free estimate.")]),
'plans':('Plans & design',[
('From the first plans to the finished project',"Before a major extension or renovation, clear plans help avoid surprises and unexpected costs. A free estimate also helps you organize your project.","MG Pro works with architects and architectural technologists to prepare custom extension, renovation and garage plans. We offer a turnkey service in Laval, Montréal, the North Shore and the Laurentians.","Major work may require municipal approvals and plans before permits can be issued. Once the plans and required authorizations are in place, our team can proceed with construction, whether you are adding a storey or redesigning your ground floor. Worksite safety and compliance with applicable standards are part of the planning."),
('Why prepare renovation plans?',"Plans define the scope, help calculate material quantities and establish a realistic budget. They also let you see the intended result and make changes before construction, when revisions can be more expensive.","We offer planning and construction expertise in Greater Montréal, the Laurentians and Laval, including Chomedey, Laval-sur-le-Lac, Duvernay, Laval-Ouest, Sainte-Dorothée, Sainte-Rose, Vimont, Auteuil and Fabreville."),
('Custom plans for your project',"Tell us about your needs and ideas. Working with architects and technologists, we develop plans that fit your renovation or extension and guide the work through to completion.")]),
'agrandissement':('Home extensions',[
('Extensions, additions and extra storeys',"If your home feels too small but you do not want to move, an extension may be worth exploring. MG Pro manages the project from the design stage, working with architects and architectural technologists.","Once you approve the plans and the required permissions are in place, we undertake the work in Laval, Montréal, the North Shore and the Laurentians. Options include adding a storey, extending the house or building a garage. We help you compare space requirements and budget, beginning with a free estimate."),
('Questions to ask before extending your home',"Start with the reason for extending: more living space, storage or a change in appearance. Check what your municipality allows, assess your budget and any financing you may need, and have the existing structure reviewed by a qualified professional.","Our architects and technologists can then prepare suitable plans. With more than 20 years of construction and renovation experience, the MG Pro team helps adapt your house to your changing needs."),
('More room for your life',"Our turnkey service covers planning, construction and the final finishes. Discuss your project with us to explore the right addition for your home.")]),
'renovation-commerciale':('Commercial renovation',[
('Spaces that reflect your business',"MG Pro renovates commercial properties in Laval, Montréal and the Laurentians. We plan the schedule around your business needs and the agreed scope, with careful attention to budget, workmanship and coordination.","From offices and shops to boutiques and restaurants, we guide the project from the free estimate to the finishing touches. We can also coordinate renovation plans to help organize the work.","We serve Laval-Ouest, Laval-sur-le-Lac, Chomedey, Fabreville, Sainte-Dorothée, Vimont, Auteuil, Sainte-Rose and Duvernay."),
('Office and commercial interiors',"Your team and your customers deserve functional, welcoming surroundings. Our services include plastering, flooring, ceramic tile and painting, as part of a carefully coordinated renovation.","We work with reliable specialist contractors who share our standards. Clear coordination helps keep your renovation moving toward the agreed result and schedule."),
('Give your business a fresh start',"Tell us about the changes you want to make. Our construction and renovation team can help turn your ideas into a practical project, with a free estimate.")]),
'bureaux-commerciaux':('Office fit-outs',[
('A workplace that works for your team',"MG Pro helps businesses in Laval, Montréal, the North Shore and the Laurentians redesign their offices. A welcoming, well-organized workplace supports your staff and the impression you make on visitors.","We assess your available space, expectations and budget before preparing a tailored layout. A free estimate sets out the proposed work. Appearance, ergonomics and day-to-day practicality are considered together."),
('The elements of an office fit-out',"Your vision and brand identity guide the materials, colours, lighting, structure and furniture. Meeting rooms, quiet work areas and collaborative spaces should respond to the needs of the people using them.","Our multidisciplinary team develops practical, attractive layouts. Once the plans are approved, we coordinate and carry out the commercial renovation."),
('Discuss your workspace',"Share your ideas and constraints with our team. We can propose a layout suited to your business and guide you from planning to the completed space.")]),
'blainville':('Renovation in Blainville',[
('Your general contractor in Blainville',"MG Pro offers free estimates for homeowners and businesses in Blainville and across the North Shore. With more than 20 years of experience, our team provides turnkey renovation management, trusted subcontractors and regular communication throughout the work."),
('Commercial renovation',"Update the appearance of your premises, adapt to business growth or improve the comfort of your staff. Our services include complete redesigns, interior improvements and building extensions."),
('Residential renovation',"As your needs and tastes change, we help you adapt your living space. Projects include kitchen and bathroom updates, basement finishing and home extensions, with durable and carefully finished results."),
('Bathroom updates',"From walk-in showers and ceramic floors to integrated lighting and vanities with stone countertops, we help translate your ideas into a practical room."),
('Basement finishing',"Additional bedrooms, a family room, home theatre, bar, storage, laundry room or workshop: your basement can serve many purposes. Our team plans and finishes the space around your needs."),
('Home extensions',"Before moving, consider an addition, an extra storey or a veranda. Our turnkey approach covers the planning and construction of your extension."),
('Plan your project in Blainville',"Discuss your goals, budget and schedule with MG Pro and request a free estimate.")])}
pages=[]
for slug,(label,sections) in translations.items():
 src=next(p for p in original['pages'] if p['slug']==slug);blocks=[{'type':'h1','text':label}]
 for section in sections:
  blocks.append({'type':'h2','text':section[0]});blocks.extend({'type':'p','text':t} for t in section[1:])
 blocks.extend({**b,'alt':'MG Pro renovation project'} for b in src['blocks'] if b['type']=='image')
 pages.append({'slug':slug,'label':label,'title':label+' in Laval, Montréal and the North Shore','description':sections[0][1][:155],'blocks':blocks})
montreal=json.loads(Path('content/montreal-en.json').read_text(encoding='utf-8'));montreal['label']='Montréal & West Island';montreal['blocks']=[b for b in montreal['blocks'] if b.get('text')!='Put your faith in the 22 years experience of this general contractor!'];pages.append(montreal)
Path('content/english.json').write_text(json.dumps(pages,ensure_ascii=False,indent=2),encoding='utf-8')
